### PR TITLE
Resources Rebranding for Overte

### PR DESCRIPTION
**Pull request by AleziaKurdis**
This PR updates many resources files with the Overte brand.
Mostly images, icons and models.

Some resource files had "Vircadia" in the name, they have been replaced by new files using "brand" instead of vircadia. _(So it will be less a problem for anyone that need to do this rebranding one day)_
The reference in the code to those files has been updated. (it's part of this PR)

**Not part this PR**: presence of "Vircadia" in text or url pointing on Vircadia side. (there are a lot to do.)

No test has been done (sorry I don't build)
Mainly the new logo in the tutorial. It can be only test with a build.

### CODE REVIEW

**Comment by vegaslon** [comment]
Builds alright and images appears in tutorial

**Comment by ksuprynowicz** [comment]
I tested the most recent client build on Linux and it works perfectly. There are still some places to rebrand but we can leave it for a next PR. I will be building Windows Installer next and will share a link for testing. We also need to test the server.

**Comment by ksuprynowicz** [comment]
I also tested Windows client and it works well, except for a few places that still need rebranding, like the logo in installer. Testing of domain server is still needed.

**Comment by AleziaKurdis** [comment]
Installer resources rebranded.
except for the file "install-folder.rsrc"
I didn't find how to edit this without a Mac.

**Comment by AleziaKurdis** [comment]
Just replaced the logo files for the installer to get better margin and more exact size to avoid a degradation in the rendering.

**Comment by ksuprynowicz** [comment]
This PR is tested pretty well by now, both on Windows and Linux. We just need a code review.

**Comment by johappel** [comment]
There are two points in the Intaller.md that confuse me a bit (may be that there is no other way at the moment):

Run Overte Builder.
    ```
    ./vircadia-builder --build server
    ```

and the default installation dir: /root/Vircadia

**Comment by ksuprynowicz** [comment]
@johappel Thanks! That root installation directory is only for Amazon Linux 2, which is deprecated by now. I think we should update build instructions in separate PR.

**Comment by ksuprynowicz** [comment]
I will also rebrand vircadia-builder soon to make it less confusing

**Pull request merged**
