### PR TITLE
 add canViewAssetURLs domain permissions

### PR DESCRIPTION
**Pull request by HifiExperiments**
redo of https://github.com/overte-org/overte/pull/40

this adds a new set of permissions to the domain server for who can view asset URLs on your domain from a script. this includes any entity property that is a URL and any avatar skeletonModelURL (besides your own). it's possible that this will break scripts for those without permissions if the scripts rely on those URLs, and obviously the check is completely on the client so hacked clients could get around it but it's still an extra layer of content protection

### Testing
- run the domain server from this PR.
- when "Can View Asset URLs" is checked, make sure create works as expected and you can see your own skeletonModelURL as well as other avatars'.
- when "Can View Asset URLs" is off, confirm that create shows a placeholder message instead of the true URLs.  you should still be able to get your own skeletonModelURL, but not others'.
- if you toggle the permission off while someone has create open, they should see the URLs change to the placeholder.  if you toggle it back on, the URLs will go back to "URL" *not the actual URL*.  but then if you close create an re-open it, they should show the real URLs.  this is due to a quirk of how create works, we could try to fix it in the future but I don't expect that people will be toggling this live a lot, so I think it's acceptable for now.

### CODE REVIEW

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR152/Overte-PR152-50b2598.tar.gz
 - https://public.overte.org/build/overte/PR152/Overte-PR152-50b2598.tar.Z
 - https://public.overte.org/build/overte/PR152/Overte-PR152-50b2598.sh

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR152/Overte-PR152-50b2598.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR152/Overte-PR152-50b2598.tar.gz
 - https://public.overte.org/build/overte/PR152/Overte-PR152-50b2598.sh
 - https://public.overte.org/build/overte/PR152/Overte-PR152-50b2598.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR152/Overte-PR152-50b2598.exe

**Comment by HifiExperiments** [comment]
@ksuprynowicz I've rebased this and made some updates to create to handle it more gracefully!

**Review by ksuprynowicz — APPROVED** [review]

**Comment by ksuprynowicz** [comment]
Everything looks fine :)
We just need to test it and we can merge.

**Comment by ksuprynowicz** [comment]
Does it break protocol?

**Comment by HifiExperiments** [comment]
@ksuprynowicz oh that's a good question...I don't think it's a protocol break in that nothing about the serialization over the network changed (just a new value in [NodePermissions.h](https://github.com/overte-org/overte/pull/152/files#diff-c83b7002283be18e6800891cb6b037349362ea52b3c26dfa9ccbc1ff9782080d) which shouldn't change the size of `Permission`), so it won't crash.  if you have a new server and an old client, the client will just ignore the setting (since it's entirely implemented client-side).  but if you have an old server and a new client...it's possible that the client would always think it didn't have permission, which isn't ideal.  so maybe we wait to merge this until we bump the protocol, or we merge it just before an RC so at least most people are on the same version?

**Comment by ksuprynowicz** [comment]
I think we should merge this before the upcoming release then, because my avatar protection PR will affect some of the same lines of code, and otherwise we would have to rebase this PR again.

**Comment by HifiExperiments** [comment]
@ksuprynowicz I'm also happy to do the rebasing if your PR gets merged first!  your changes are definitely cleaner, I didn't really need to override `getSkeletonModelURLFromScript` so it's just adding the permission check to `AvatarData::getSkeletonModelURLFromScript()`

**Comment by vegaslon** [comment]
Out of curiosity, does this take into account avatar entities? Will it block any scripts in them being able to access their own urls?

**Comment by HifiExperiments** [comment]
@vegaslon ah!  it doesn't currently but that's a good idea, I think I can make it so you can always access your own avatar entities' urls

**Comment by vegaslon** [comment]
If that is possible the avatar app will appreciate it. The urls are used to make tags for all the attachments.

**Comment by ksuprynowicz** [comment]
The scripts can already get their own URLs with Script.resolvePath("") and I don't think this PR blocks that. Script also typically knows filenames of assets it spawns, so their full URLs can be resolved with Script.resolvePath("").
Is there anything that this PR currrently breaks?

**Comment by vegaslon** [comment]
I do not mean only the urls of scripts but also the url of any avatar entity assets. Yes as stated this pr breaks functionality of the avatar app when used on a domain.

**Comment by ksuprynowicz** [comment]
Which parts of avatar app are broken?

**Comment by HifiExperiments** [comment]
this PR only affects `Entities.getEntityProperties` and `MyAvatar.skeletonModelURL`.  vegaslon is referring to the ability to get the url properties of your own avatar entities, which this PR currently breaks and I need to fix.

I actually need to check, does the avatar app even use avatar entities or does it use wearables/attachments? (it doesn't matter too much since we should [make them the same thing](https://github.com/overte-org/overte/issues/932) anyways)

if there are other methods/getters that we'd like to protect with this flag, I can do that too

**Comment by vegaslon** [comment]
The wearable section of it, it uses the URL of the avatar entities to create a name for each wearable. When it no longer has access to these names it is forced to use generic naming to identify each wearable and making it impossible to know which wearable you are adjusting in the menus beside using trial and error and there is no guarantee of what order your wearables will show in the menu after each load.

**Comment by HifiExperiments** [comment]
I've rebased this and made it so you can always get your own avatar entities' urls.  the avatar app did in fact use attachments, *not* avatar entities, so it is unaffected by this change

I had also missed a few properties initially.  besides MyAvatar.skeletonModelURL, the following entity properties are protected:
- collisionSoundURL
- compoundShapeURL (particles, models, and zones)
- modelURL
- filterURL
- sourceUrl
- scriptURL
- xTextureURL
- yTextureURL
- zTextureURL
- materialURL
- materialData
- imageURL
- textures (which is an old weird thing for image entities)
- ambientLight.ambientURL
- animation.url
- grab.equippableIndicatorURL
- skybox.url

**Comment by ksuprynowicz** [comment]
I will test the newest version tomorrow, and if everything works then we can merge this PR and build the release candidate :)

**Comment by ksuprynowicz** [comment]
I just tested it on a local copy of Overte_hub, and everything works as intended. I think it's safe to merge and then we can make release candidate builds.

**Comment by HifiExperiments** [comment]
thank you @ksuprynowicz!!

**Pull request merged**
