### PR TITLE
[ Unified UI ] Settings

### LINKED ISSUE #1146: [ Unified UI ] Settings App Update & Refactoring
The settings application(s) that exist presently in Overte are all Over-te place. There exist several separate QML based settings applications that each target one specific area of the overall settings of the application. Some users have also expressed frustration with the sometimes confusing layout. I have also had issues with trying to find a specific setting only to find I just can not see it because I am not in a specific view. This made walking though new users with specific settings very difficult. 

Graphics Settings: https://github.com/overte-org/overte/blob/master/interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
Controls: https://github.com/overte-org/overte/blob/808135b6c4a63c12f8dd35fc8aa9741a69ad3263/interface/resources/qml/hifi/tablet/ControllerSettings.qml
Audio: https://github.com/overte-org/overte/blob/808135b6c4a63c12f8dd35fc8aa9741a69ad3263/interface/resources/qml/hifi/audio/Audio.qml

These applications were also built at different times by different people under different design principles. These apps should be consolidated into a single cohesive application that neatly organizes all settings. Improvements must be made to the whole construction of the application UI so that future maintenance is quick and painless.  

Image
Image
Image

### PR DESCRIPTION
**Pull request by Armored-Dragon**
Replacement for the many existing settings apps. 
This replacement consolidates all of the interface settings into a single organized application.

Closes #1146 

Example pictures / other media will be published as work gets done.

Task list:
- [ ] Basic / Advanced view
- [ ] Cohesive design
- [x] Graphics
- [ ] Controls 
- [ ] Calibration
- [ ] Audio
- [ ] Security / Privacy

### CODE REVIEW

**Comment by AleziaKurdis** [comment]
Can we expect to have a way to open directly "Calibration"? (and other tab too) The current one is on a tab and and it is not directly openable. And for people using intensively full body tracking, we do have to go to that UI very often (reason why I have made the Callibration app button as a shortcut for it... but it is sadly not direct as it could be.)

**Comment by Armored-Dragon** [comment]
> Can we expect to have a way to open directly "Calibration"? (and other tab too) The current one is on a tab and and it is not directly openable. And for people using intensively full body tracking, we do have to go to that UI very often (reason why I have made the Callibration app button as a shortcut for it... but it is sadly not direct as it could be.)

Yes of course! I too use full body a lot and I also have a grudge about how hidden the calibration is. It's too early to be able to tell you what it will look like but at bare minimum it will be very easily findable.

**Comment by JulianGro** [comment]
Maybe automatically adding a calibrate button to the tablet, when additional trackers are detected, would make sense. VRChat does this as well.
Rather than adding a full button, there is also space at the top, where the clock and the microphone button is where we could add more buttons. (We could also add a button to switch between standing mode and seated mode there.)

**Comment by AleziaKurdis** [comment]
> (We could also add a button to switch between standing mode and seated mode there.)
Is it not automatic ?

**Comment by Armored-Dragon** [comment]
Graphics page: 
image

As of right now it is not an improvement over the existing graphics settings. Until I get a stylized design finished for all of the UI elements they will also be using the default QML styles. As such, the page(s) look very basic. This will change in the future.

**Comment by Armored-Dragon** [comment]
Commit `7beb1ad` had animation improvements. Here's what they look like:

[animations.webm](https://github.com/user-attachments/assets/91732fbc-977d-4632-9b93-388727de1efa)

**Comment by Armored-Dragon** [comment]
This has been superseded by https://github.com/overte-org/overte/pull/1240.

**Pull request closed without merging**
