### PR TITLE
Avatar Smoothing

### LINKED ISSUE #567: accelerationFilterApp.js (preinstalled) does not work
it has links to the old "HF_Public" bucket that are no longer valid.

### LINKED ISSUE #571: Full-body tracking has way too much smoothing applied to it
The full-body tracking has a lot of smoothing applied to it to the point that fast movement isn't visible

### PR DESCRIPTION
**Pull request by Armored-Dragon**
Resolves #567 and resolves #571.
Existing applications in the repo are incomplete, contain broken links, or use non-implemented features.
This will consolidate existing "in-dev" applications into a single functional app.

### CODE REVIEW

**Comment by Armored-Dragon** [comment]
Also, in this pull request I removed a file 'AccelerationFilter.js'. Currently in the master branch it tries to use ["accelerationLimiter" type of filter](https://github.com/overte-org/overte/blob/9c78c8fb3a67c00e37f16cc66a3212f64cd6eae8/scripts/developer/accelerationFilterApp.js#L16C28-L16C47). There appears to be [code](https://github.com/search?q=repo%3Aoverte-org%2Foverte%20accelerationLimiter&type=code) referencing it but it is not mentioned in the docs, nor is this exposed via API.

**Comment by ksuprynowicz** [comment]
Both `accelerationLimiter` and `exponentialSmoothing` filters are registered in `libraries/controllers/src/controllers/impl/Filter.cpp`. Do the scripts using them not work currently?

**Comment by Armored-Dragon** [comment]
accelerationLimiter does not work at all and logs an error relating to 'accelerationLimiter' not being a valid 'type'. exponentialSmoothing *may* work; There is no UI to interact with it as the [HTML link](https://github.com/overte-org/overte/blob/c0dfbc8e4d3393dd6a3fc231ae932cd8166259f1/scripts/developer/exponentialFilterApp.js#L92) does not exist. I did originally use a modified version of this file to originally test to make sure 'exponentialSmoothing' was a valid type.

**Comment by ksuprynowicz** [comment]
Can we move these to script-archive instead of deleting? They might become useful in the future if we figure out why accelerationLimiter is not available on script engine side.

**Comment by SilverfishVR** [comment]
I think @daleglass has the missing files from HF_Public:
`/tony/html/accelerationFilterApp.html`
`/tony/icons/tpose-i.svg`
`/tony/icons/tpose-a.svg`

But if _accelerationLimiter_ is broken it's not much use.
🤔 perhaps there was another app, on the marketplace mayhaps.

**Review by ksuprynowicz — APPROVED** [review]

**Pull request merged**
