### PR TITLE
Domain wizard

### PR DESCRIPTION
**Pull request by ksuprynowicz**
Things to do:

- Fix the wizard continuing if your https authentication configuration is wrong. (It shows an error but still continues)
- Connecting your Domain to the Metaverse server is huge hackery. That is the one thing Kalilas wizard did better.
- The code for setting a place name is commented out. Not sure what to do about that, or if we even should do something about that for now.
- The "Share your Domain" field on the "Congratulations" page is empty. We could just disable the congratulations page again, but it did make me realize that we don't tell our users how to actually connect to their Domain.

### CODE REVIEW

**Comment by ksuprynowicz** [comment]
I looked through the code and everything seems fine. I also tested it on Linux.

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR150/Overte-PR150-3a539ee.dmg

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR150/Overte-PR150-d24b46c.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR150/Overte-PR150-d24b46c.exe

**Review by JulianGro — APPROVED** [review]
Connecting to a directory server on start is still really hacky. Apparently it doesn't even give you a proper error when entering a wrong password.

Everything else seems to work fine in practice.
All in all, I think this is almost as good as the old/new wizard this is replacing.

The code changes are all logical as well.

**Comment by ksuprynowicz** [comment]
Thanks! Another advantage is that this version is extremely easy to extend and maintain.
I will merge it right now :)

**Pull request merged**
