### PR TITLE
Fix build warnings, second iteration

### PR DESCRIPTION
**Pull request by daleglass**
This fixes more warnings, most in server code. Getting there!

There's still a bunch of sprintf stuff to deal with, but this should be good to go in if I don't have the time to finish that bit.

### CODE REVIEW

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR86/Overte-PR86-b708e28.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR86/Overte-PR86-b708e28.tar.Z
 - https://public.overte.org/build/overte/PR86/Overte-PR86-b708e28.sh
 - https://public.overte.org/build/overte/PR86/Overte-PR86-b708e28.tar.gz

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR86/Overte-PR86-b708e28.tar.gz
 - https://public.overte.org/build/overte/PR86/Overte-PR86-b708e28.sh
 - https://public.overte.org/build/overte/PR86/Overte-PR86-b708e28.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR86/Overte-PR86-b708e28.exe

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR86/Overte-PR86-c70eb56.dmg

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR86/Overte-PR86-c70eb56.tar.gz
 - https://public.overte.org/build/overte/PR86/Overte-PR86-c70eb56.tar.Z
 - https://public.overte.org/build/overte/PR86/Overte-PR86-c70eb56.sh

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR86/Overte-PR86-c70eb56.tar.gz
 - https://public.overte.org/build/overte/PR86/Overte-PR86-c70eb56.tar.Z
 - https://public.overte.org/build/overte/PR86/Overte-PR86-c70eb56.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR86/Overte-PR86-c70eb56.exe

**Review by akamicah — APPROVED** [review]
Code looks fine

**Comment by akamicah** [comment]
Build tested and looking good. A few `class-memaccess` warnings remain but can be looked at another time.

**Pull request merged**
