### PR TITLE
Ambient Light Color

### LINKED ISSUE #6: Add an ambientLight.color property to Zone entity.
Since can play with skybox.color, it would make sense to be able to have the counterpart in ambient light, to be able to stay consistent visually.

### PR DESCRIPTION
**Pull request by HifiExperiments**
Closes #6 

Adds `ambientLight.ambientColor` to Zone Entities, matching the behavior of `skybox.color`.

## Funding

This project is funded through [NGI0 Entrust](https://nlnet.nl/entrust), a fund established by [NLnet](https://nlnet.nl) with financial support from the European Commission's [Next Generation Internet](https://ngi.eu) program. Learn more at the [NLnet project page](https://nlnet.nl/project/Overte).

[NLnet foundation logo](https://nlnet.nl)
[NGI Zero Logo](https://nlnet.nl/entrust)

### CODE REVIEW

**Comment by ksuprynowicz** [comment]
I just tested on Linux, and all works well, including values persisting when restarting server and client.

**Comment by ksuprynowicz** [comment]
Oops... I didn't test it well enough. It looks like it has exactly same but as unlit PR, with Create App misreporting property:
image

**Comment by HifiExperiments** [comment]
huh...I wonder what I could have broken that would cause only new properties like these to report incorrectly!

**Comment by ksuprynowicz** [comment]
Another thing I noticed is that the property in Create App keeps the value of the last set color, so for example on the screenshot I created cyan-colored zone, and then red-colored zone. On the screenshot cyan zone is selected, but color is misreported as red:
image

**Comment by HifiExperiments** [comment]
@ksuprynowicz fixed!  adding new entity properties suuuuuucks.  I have a few more new properties that I'm working on, and then I have an plan now of how to greatly simplify the whole process.

**Comment by ksuprynowicz** [comment]
Nice!
I just tested it and everything works perfectly now :)

**Review by ksuprynowicz — APPROVED** [review]
All looks good :)

**Pull request merged**
