### PR TITLE
Fix most of the crash causes on script engine reload/shutdown

### PR DESCRIPTION
**Pull request by ksuprynowicz**
Script reload works pretty well now.
I also temporarily disabled forced termination of script threads because it was completely unsafe and would always cause crashes. We need to do it in a better way in later PR.

### CODE REVIEW

**Review by AnotherFoxGuy — APPROVED** [review]
Seems to work fine on Windows, reloading all scripts and reloading all content now no longer crashes the interface

**Comment by SilverfishVR** [comment]
For me, events are repeated 5 times, so for each `mouseReleaseOnEntity` or `hoverEnterEntity` in a entity client script it is triggered 6 times:
Screenshot 2023-08-19 030441
scrip used for testing:
https://www.dropbox.com/scl/fi/fogdjy9nmyqgwkzdkrn0g/Test_minimal_entityClientScript2.js?rlkey=q20c0eylgo9ahvqht1v71c7zy&dl=1

**Comment by ksuprynowicz** [comment]
@SilverfishVR I just tested the newest version and it looks like issue with entity scripts is fixed. If you have some time please let me know if it works on newest build for you too.

**Review by daleglass — APPROVED** [review]

**Comment by SilverfishVR** [comment]
👍 It does indeed seem to work now 👍

**Pull request merged**
