### PR TITLE
Notifications: Local Entities, emissive, HMD bugs fixes, new HMD positioning, settings ON/OFF.

### PR DESCRIPTION
**Pull request by AleziaKurdis**
This PR gives some love to the notification system

Issues: 
- The snapshot notification was not emissive, it was a pain to see the result under some conditions.
- It was using deprecated Overlays in HMD that wasn't supporting emissivity.
- The snapshot was very down, sometime half in the floor, with orientation and positioning issues
- It was also a nuisance  because it was ruining shot by just being displayed.

Here's what has been done:
- All the usage of deprecated 3d overlays have been changes to Local Entities (Only the addEntity was necessary.)
- All the notifications are now unlit / emissive (it needed Local entity to achieved that.)
- The HMD has been repositionned to be visible. (This is a try, I think it is better. A bit on the right but just a bit higher than your eyes, vertical. Let me know what you think, we can adjust that)
- Many bug fix, mainly for the HMD mode. (it was a mess regarding positionning, orientation, size, ratio and not rely on the parenting correctly.
- I added a setting to switch on/off the "snapshot" related notifications (because they are often a nuisance during capture sessions.)

**NOTE: The setting still need to be plugged in the the compiled side.** 
@74hc595, you told me that you could add it for me... here are the requirement:
setting key: "**snapshotNotifications**"
datatype: **boolean**
default value: **true**
Caption: "**Snapshot notifications**"
Location: **General Settings > Snapshot** (section)

### CODE REVIEW

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR189/Overte-PR189-1ca846d.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR189/Overte-PR189-1ca846d.exe

**Review by ksuprynowicz — APPROVED** [review]
All looks fine to me :)
I will try adding setting tomorrow.

**Comment by ksuprynowicz** [comment]
I added the setting for disabling snapshot notifications in preferences. Everything seems to work correctly.

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR189/Overte-PR189-c35c4b4.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR189/Overte-PR189-c35c4b4.exe

**Comment by ksuprynowicz** [comment]
I tested it on Linux and Windows and it works fine.

**Pull request merged**
