### PR TITLE
Places App.: Persisted Maturity Filter and Default value for Newbies.

### PR DESCRIPTION
**Pull request by AleziaKurdis**
This PR makes the **Places App.** "**Maturity**" **filter** persisted in a setting.
It also define the default value that the "Maturity" filter will have for a new user.

The default value will have  "**teen**" and "**everyone**" set.
_(so "adult", "mature" and "unrated" NOT set.)_

Please let me know if you have concerns regarding this default value.

### CODE REVIEW

**Comment by ksuprynowicz** [comment]
Making the maturity filter persistent is a really nice improvement.
I'm worried about unrated not being set though, since that's default value, and most people will never discover this setting. Maybe a popup on first launch would be possible?

**Comment by AleziaKurdis** [comment]
I finally set the default value to: **["adult", "mature", "teen", "everyone", "unrated"]** _(everything visible)_
  
I evaluated the idea to have a prompt to let the user if he want it restricted or not and frankly it is overkill _(implement the communication to push the info to the UI, and probably have custom UI  to work in HMD, all that for just for a one time use.)_
  
But since the filter is right in front of our eyes...
image
I think it is not so bad.
   
What I wanted to address with this PR, is if someone would have set the maturity as restricted, then it will be persisted, protecting from any "dangerous" surprise in the place list. (which wasn't the case today)
  
It would be always possible to address other restricted content later (not necessarily soon). Like adding a "**parental/business control**" locking some options in the **maturity filter** and lock the ability to **manage the regions** (dir. servers)

**Review by daleglass — COMMENTED** [review]
I'm not well versed in UI code and don't quite understand,  what's the deal with the timestamps and INTERCALL_DELAY?

Maybe something in the API needs improving so that this is not necessary?

**Comment by AleziaKurdis** [comment]
> I'm not well versed in UI code and don't quite understand, what's the deal with the timestamps and INTERCALL_DELAY?
> 
> Maybe something in the API needs improving so that this is not necessary?

The html button's onclick is sometime triggered multiple time, this is a parade against this.
It is certainly not expected, but it was happening during the development of this tool and maybe it still happen.

**Review by ksuprynowicz — APPROVED** [review]
Everything looks good :)

**Pull request merged**
