### PR TITLE
Update Qt on Windows to 5.15.5 and QtWebengine to 5.15.11

### PR DESCRIPTION
**Pull request by ksuprynowicz**

### CODE REVIEW

**Comment by JulianGro** [comment]
Can you put a date, the KDE commit sha, and the architecture in the name?
Without a date the sorting gets horrible, without a commit sha we won't know if an update is available, and not having an architecture gets messy once we support more architectures on Windows.
Something like `qt5-install-5.15.5-2022.08.01-kde_ea4efc067b47c11b1aac61668afd8578a6834f5b-windows-x86_64.tar.gz`

By the way, you can also use xz compression instead of gzip to save a lot on file size.

**Comment by ksuprynowicz** [comment]
Sure! It's a good idea. I was thinking about xz, but was not sure if it would work. I'll fix it tomorrow.

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR146/Overte-PR146-cd721ff.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR146/Overte-PR146-cd721ff.tar.gz
 - https://public.overte.org/build/overte/PR146/Overte-PR146-cd721ff.sh
 - https://public.overte.org/build/overte/PR146/Overte-PR146-cd721ff.tar.Z

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR146/Overte-PR146-cd721ff.tar.Z
 - https://public.overte.org/build/overte/PR146/Overte-PR146-cd721ff.sh
 - https://public.overte.org/build/overte/PR146/Overte-PR146-cd721ff.tar.gz

**windows-2019, full**
 - https://public.overte.org/build/overte/PR146/Overte-PR146-cd721ff.exe

**Review by JulianGro — APPROVED** [review]
There really isn't much to code review.
I think it just needs a smoke-test on Windows.

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR146/Overte-PR146-a56dd4d.dmg

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR146/Overte-PR146-a56dd4d.tar.gz
 - https://public.overte.org/build/overte/PR146/Overte-PR146-a56dd4d.sh
 - https://public.overte.org/build/overte/PR146/Overte-PR146-a56dd4d.tar.Z

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR146/Overte-PR146-a56dd4d.sh
 - https://public.overte.org/build/overte/PR146/Overte-PR146-a56dd4d.tar.Z
 - https://public.overte.org/build/overte/PR146/Overte-PR146-a56dd4d.tar.gz

**windows-2019, full**
 - https://public.overte.org/build/overte/PR146/Overte-PR146-a56dd4d.exe

**Pull request merged**
