### PR TITLE
Protocol changes -> master

### PR DESCRIPTION
**Pull request by HifiExperiments**
This PR includes all of the following changes:
- Mirrors + Portals: https://github.com/overte-org/overte/pull/721
- Entity Tags: https://github.com/overte-org/overte/pull/748
- Web Entity wantsKeyboardFocus: https://github.com/overte-org/overte/pull/814
- Audio Zones: https://github.com/overte-org/overte/pull/847
- GPU Particles: https://github.com/overte-org/overte/pull/884
- Smooth Model Animations: https://github.com/overte-org/overte/pull/889
- Sound Entities: https://github.com/overte-org/overte/pull/894
- Unlit Shapes: https://github.com/overte-org/overte/pull/1041
- Ambient Light Color: https://github.com/overte-org/overte/pull/1043
- Zone Tonemapping + AO: https://github.com/overte-org/overte/pull/1050
- Remove Attachments: https://github.com/overte-org/overte/pull/1069
- Graphics Settings: https://github.com/overte-org/overte/pull/1053
- Model Load Priority: https://github.com/overte-org/overte/pull/1085
- Automated entity property serialization: https://github.com/overte-org/overte/pull/1098
- Text verticalAlignment: https://github.com/overte-org/overte/pull/1111

### CODE REVIEW

**Comment by HifiExperiments** [comment]
from my side, this should be ready to merge now, unless anyone else wanted to include other protocol changes for the next release!

personally, I don't think it needs its own CR/QA since each individual PR was reviewed and the whole thing will be tested again as part of the RC, and if any issues do arise I can fix them directly in master, but I leave that to others to decide

**Comment by JulianGro** [comment]
I was meaning to do a new release candidate today.
Still seems like a good idea to me; Then we will have a release right before the protocol changes merge.

**Comment by HifiExperiments** [comment]
so...I have a fair number of PRs I've been working on that depend on various changes in this branch, and I'm also worried about conflicts piling up if it sits too long (there are already several new PRs against master that will lead to conflicts once merged).  I'll also have a bit less time to work on things starting in a few weeks, so I'd love to get this wrapped up.

do we have a plan/timeline for the upcoming release, or anything I could help with?  or, since it's already been tagged, could we think about merging this sometime soonish?  I think that'll be the best way to get people using and testing it anyways.  removing the voxel autodelete could also come later, especially since #830 is not included in this (and in fact, that PR already includes the removal of the auto delete: https://github.com/overte-org/overte/pull/830/files#diff-637dfca649b67c61e00fd48f256591e8113cbca5cf791da6ff6e3e6d9c6dd303L1120)

**Comment by ksuprynowicz** [comment]
@HifiExperiments Can I merge it today? I'll do one last short round of testing before merging of course.

**Pull request merged**
