### PR TITLE
Zone properties for tonemapping and ambient occlusion

### LINKED ISSUE #934: Allow per-zone AO and tonemapping settings

### PR DESCRIPTION
**Pull request by HifiExperiments**
closes #934

adding a new entity property?  annoying.  adding two new zone render property groups?  THOUSANDS OF LINES OF GARBAGE.

this adds a bunch of new Zone properties for configuring tonemapping and ambient occlusion.  the tonemapping properties are simple but the ambient occlusion properties are fairly technical and confusing...it would be great if folks could try them out and see if they make sense.  we might need different defaults for the different techniques, and the property descriptions might also need to be clearer.

thank you again to @AleziaKurdis for the create icons!

## Funding

This project is funded through [NGI0 Entrust](https://nlnet.nl/entrust), a fund established by [NLnet](https://nlnet.nl) with financial support from the European Commission's [Next Generation Internet](https://ngi.eu) program. Learn more at the [NLnet project page](https://nlnet.nl/project/Overte).

[NLnet foundation logo](https://nlnet.nl)
[NGI Zero Logo](https://nlnet.nl/entrust)

### CODE REVIEW

**Review by ksuprynowicz — APPROVED** [review]
Everything looks fine :)

**Comment by ksuprynowicz** [comment]
I just tested it and everything works perfectly on Linux in Desktop mode.
We should also test it in VR, since side tabs in Properties in Create App for the zone might not fit on the tablet.

**Comment by ksuprynowicz** [comment]
I tested it on Windows in VR, and the side tabs work perfectly in VR but it turns out that there is a VRAM usage issue with SSAO - it uses up all the VRAM on RTX 3090 I tested it on, resulting in about 4 FPS in VR and 11 FPS in desktop mode. HBAO works perfectly fine though. I also checked with the current stable release and same issue happens there when turning on SSAO. I'm using 556.12 Nvidia driver.
20240717_175338_MixedReality
obraz
obraz

**Comment by JulianGro** [comment]
@ksuprynowicz are you positive that the video memory is actually full and Overte isn't just reporting incorrectly?

**Comment by ksuprynowicz** [comment]
> @ksuprynowicz are you positive that the video memory is actually full and Overte isn't just reporting incorrectly?

I just checked it, and you are right. It's just misreporting it, but severe performance drop is there.

**Comment by ksuprynowicz** [comment]
The weirdest part that I'm not getting almost any performance decrease with SSAO on Linux on the same computer, it's only on Windows.

**Comment by ksuprynowicz** [comment]
Could someone else also test on Windows on the same Nvidia driver version (556.12)?

**Comment by ksuprynowicz** [comment]
On Linux I have driver version 535, so an older one.
Either way the issue is not related to this PR, and since PR itself works perfectly well, maybe we could merge it and I'd open an issue for SSAO performance?

**Comment by JulianGro** [comment]
> Could someone else also test on Windows on the same Nvidia driver version (556.12)?

Does this only happen in VR? In desktop mode on 556.12, I get a 50% frametime hit on SSAO and a 100% frametime hit on HBAO.

**Comment by HifiExperiments** [comment]
can you tell if there's any particular property that is most impacting it?  I wonder if the Sampling Amount is too high.  at the default value of 0.5 SSAO is doing 32 samples which is quite a bit.

there's actually a lot of similarities between the two implementations, most of the code in `AmbientOcclusionEffect::run` is the same.  we have a few profile ranges in there for the different passes, I forget exactly how you see those values...

**Comment by ksuprynowicz** [comment]
For me it looks like Sampling Amount and other parameters don't affect the performance in significant way. Frame time changes a bit with Resolution Level, but is still about 10 times too high even in desktop mode..
I captured frames for SSAO and HBAO with RenderDoc, and the most significant difference is that SSAO uses glGenerateMipmap, which may be the cause? The weirdest part is that with 535 Nvidia drivers on Linux there's no performance hit to SSAO almost at all.

**Comment by ksuprynowicz** [comment]
The resolution seems to be having most significant impact. I run Overte in 4K in desktop mode and about 8K total in VR.

**Comment by JulianGro** [comment]
@ksuprynowicz do you have ReBAR on your system?

**Comment by ksuprynowicz** [comment]
> @ksuprynowicz do you have ReBAR on your system?

I have Above 4G Decode, but not ReBAR.

**Comment by JulianGro** [comment]
I wonder if it's just running out of bandwidth to the GPU. I seem to remember hearing that ReBAR doesn't matter as much on Linux, because the kernel already resizes BAR depending on the available BAR size. This would at least explain why you are having issues on Windows and not on Linux. Of course, I don't know much about this and I have no idea if the Nvidia driver on Linux would even take advantage of this.
Technically I could test 4k and 8k as well, but that will run slow just because my GTX 1080 isn't powerful enough.
Last time I reported an issue to Nvidia they fixed it a couple of months later. Maybe you could post an apitrace or something on their developer forum?

**Comment by HifiExperiments** [comment]
I wouldn't be surprised if it's some driver thing going on.  HBAO does have its own mip generation but it does so with a custom pipeline (for...some reason).

**Comment by JulianGro** [comment]
I tried running in 4k on my GTX 1080. Turns out that it runs quite well. The GTX 1080 doesn't support ReBAR.
Screenshot 2024-07-18 231151
overte-snap-by--on-2024-07-18_23-11-08

**Comment by HifiExperiments** [comment]
thinking about this more, it’s going to be difficult to debug.  maybe we just disable SSAO for now?  I’m thinking vulkan might affect this so we can revisit it after that?  I could either just not expose SSAO to Create, or I could not expose it to scripts at all

**Comment by JulianGro** [comment]
Yeah, maybe just remove it from the Create app and add a comment in the JSDoc about this issue and that we should re-enable it on Vulkan. Then people could still access it from the script engine and we won't forget that SSAO exists.
HBAO is slightly heavier on my system, but in my very limited testing it also looked a lot better.

**Comment by ksuprynowicz** [comment]
Maybe we could keep it, but add a warning there about possible performance impact in the Create App? Or disable it in Graphics settings by default?

**Comment by ksuprynowicz** [comment]
It's also very possible that for some reason this issue is only happening on my computer, so then this PR would be safe to merge in current form. I think we could merge it and see before next release if issue is there for anyone else.

**Comment by HifiExperiments** [comment]
I definitely don't want to tank your performance, especially since SSAO is the default option!  it'll be easier to toggle since it'll be exposed in the graphics settings, but still, if it's happening to you it's probably going to affect others too.

I think doing as Julian suggests will let us still test both modes without making the default unusable for you.  and we can always keep adjusting the default values to balance perf and visuals

**Comment by HifiExperiments** [comment]
I've changed the default to HBAO for now and removed the dropdown from Create (but you can still set it to SSAO via scripting)

if that's ok with everyone for now, this is ready to merge from my end!

**Comment by ksuprynowicz** [comment]
Nice!
I'm working on Vulkan currently so hopefully soon the issue will be resolved and we can add SSAO option back to Create App again (and add AMD CACAO too).

**Pull request merged**
