### PR TITLE
Fix metallic fbx

### PR DESCRIPTION
**Pull request by daleglass**
It was discussed on Discord that the recent FBX changes broke metallic surfaces for some FBX objects. This should do it.

### CODE REVIEW

**Comment by JulianGro** [comment]
Wouldn't this break if roughness and metallic are both 0?

**Review by JulianGro — CHANGES_REQUESTED** [review]
As expected, if the ReflectionFactor is 0 (metallic 0 and roughness maximum), the asset doesn't get displayed properly.
Bildschirmfoto vom 2023-01-08 20-25-05
Bildschirmfoto vom 2023-01-08 20-38-58

**Comment by JulianGro** [comment]
[FBX_metallic_export.zip](https://github.com/overte-org/overte/files/10369337/FBX_metallic_export.zip)
One of the test cubes has a material called "Metallic0".

**Comment by daleglass** [comment]
Wait, ReflectionFactor=0 is maximum reflection rather than none? That's weird.

**Comment by JulianGro** [comment]
> Wait, ReflectionFactor=0 is maximum reflection rather than none? That's weird.

No, it is no metallic and maximum roughness.
So it is as matte and non-metallic as possible.

**Comment by JulianGro** [comment]
Rather than checking if `REFLECTION_FACTOR` is `0`, we should check if `REFLECTION_FACTOR` exists at all.
Because having a `REFLECTION_FACTOR` means that this is a PBR material and needs to be treated as such.

Alternatively, if the old Blender FBX exporter was just broken, we could check for the Blender version. But I think the proper way is to check if `REFLECTION_FACTOR` exists or not.

**Comment by AleziaKurdis** [comment]
Tested. My content is back to normal.

**Pull request closed without merging**
