### PR TITLE
Templated render stages

### PR DESCRIPTION
**Pull request by HifiExperiments**
we have a lot of XXXXStage classes, which are responsible for passing data from various places to the various tasks that actually render different effects (like the skybox, bloom, AO, etc.).  as we've added more, they've gotten a bit out of control, and it's cumbersome to add more.  the classes were all very similar, so I've created some templated classes in Stage.h to deduplicate a lot of code.

### CODE REVIEW

**Review by ksuprynowicz — APPROVED** [review]
This is really nice :)
It will make work on renderer a lot easier

**Comment by ksuprynowicz** [comment]
I tested it in desktop mode and everything works perfectly, we just need to test in VR now.

**Comment by ksuprynowicz** [comment]
I had a crash with this message, but it seems tricky to reproduce and it's possible that it's unrelated:
```
[11/28 22:41:32] [WARNING] [default] Failed to get a valid storageView for faceSize= 16384   faceOffset= 5570740 out of valid file  "/home/ksuprynowicz/.local/share/Overte/Interface/ktx_cache/60d2133ec824c215837adef82a73ed53.ktx"
```

**Comment by ksuprynowicz** [comment]
Other than this it works well in desktop mode, everything renders correctly.

**Comment by HifiExperiments** [comment]
yeah definitely unrelated, looks like maybe ktx corruption.  this was just purely refactoring how we pass around some objects, basically if lighting and effects are working then it’s all good!  thank you for testing

**Comment by ksuprynowicz** [comment]
I will test it in VR and then I think it will be safe to merge

**Comment by ksuprynowicz** [comment]
Works perfectly in VR too :)

**Pull request merged**
