### PR TITLE
Add mouseLook script to default scripts.

### PR DESCRIPTION
**Pull request by Armored-Dragon**
Mouse look is a feature available in the Overte control settings, however it is not functional without this script running. When you clear running scripts and reload all scripts, mouseLook never gets added, breaking the functionality.

### CODE REVIEW

**Review by ksuprynowicz — APPROVED** [review]

**Comment by Armored-Dragon** [comment]
MouseLook.js seems to try to start itself via the [controllerScripts.js](https://github.com/overte-org/overte/blob/a651b6b9780e203600f19d4c3aa938239f3bc3dd/scripts/system/controllers/controllerScripts.js), however this does not seem to start itself.

**Comment by ksuprynowicz** [comment]
Ooops... I'm sorry, I didn't notice earlier but it's already loaded as one of the controller scripts. That's why it doesn't show up in running scripts.
It's loaded here:
https://github.com/overte-org/overte/blob/e05c79ca962d853be41236304dadba2ba9af0d44/scripts/system/controllers/controllerScripts.js#L22

**Comment by Armored-Dragon** [comment]
> Ooops... I'm sorry, I didn't notice earlier but it's already loaded as one of the controller scripts. That's why it doesn't show up in running scripts. It's loaded here:
> 
> https://github.com/overte-org/overte/blob/e05c79ca962d853be41236304dadba2ba9af0d44/scripts/system/controllers/controllerScripts.js#L22

The thing is that it does not seem to execute from the controller scripts. The keybinding does not work and it never gets put into a mouselook state.

**Comment by ksuprynowicz** [comment]
I think we should remove it from controller scripts as a part of this PR and then merge.

**Comment by ksuprynowicz** [comment]
Or we could make it work as a part of controller scripts and save some RAM on one less V8 isolate.

**Comment by ksuprynowicz** [comment]
Earlier it seemed to work without being in default scripts so I wonder what changed

**Comment by Armored-Dragon** [comment]
Superseded by #1086.

**Pull request closed without merging**
