### PR TITLE
Add Ubuntu 20.04 Qt package

### PR DESCRIPTION
**Pull request by JulianGro**
This PR adds a prebuilt Qt package for Ubuntu 20.04 in preparation for Ubuntu 20.04 server packages.

### CODE REVIEW

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR159/Overte-PR159-10a98c6.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR159/Overte-PR159-10a98c6.tar.gz
 - https://public.overte.org/build/overte/PR159/Overte-PR159-10a98c6.tar.Z
 - https://public.overte.org/build/overte/PR159/Overte-PR159-10a98c6.sh

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR159/Overte-PR159-10a98c6.tar.Z
 - https://public.overte.org/build/overte/PR159/Overte-PR159-10a98c6.tar.gz
 - https://public.overte.org/build/overte/PR159/Overte-PR159-10a98c6.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR159/Overte-PR159-10a98c6.exe

**Review by ksuprynowicz — APPROVED** [review]
Looks fine in my opinion. The only question I have is if the apt-get commands are running inside the docker container. If not then in some cases `apt-get -y` could ruin host OS witout asking by automatically uninstalling crucial system packeges.

**Comment by ksuprynowicz** [comment]
Would it be possible to build it with QtWebengine 5.15.11? I'm worried that 5.15.5 might have some vulnerabilities that were patched in later version.

**Comment by JulianGro** [comment]
> Looks fine in my opinion. The only question I have is if the apt-get commands are running inside the docker container. If not then in some cases `apt-get -y` could ruin host OS witout asking by automatically uninstalling crucial system packeges.

As far as I know, it is not possible to specify commands in a Dockerfile that run outside of Docker.

> Would it be possible to build it with QtWebengine 5.15.11? I'm worried that 5.15.5 might have some vulnerabilities that were patched in later version. Of course only if the package would be intended for client too. If it's for server I think it's fine like it is.

It is intended only for the server, but it uses QtWebEngine 5.15.11.

**Pull request merged**
