### PR TITLE
Remove hifi screenshare (updated)

### PR DESCRIPTION
**Pull request by daleglass**
PR #435, rebased.

Original text below:

> Cherry-picked and updated from Tivoli [dd5b6ea6ee5597a06603e16509640e7ed18106bb](https://github.com/overte-org/tivolicloud/commit/dd5b6ea6ee5597a06603e16509640e7ed18106bb)
>
> As much of a hoarder as I am, I really don't think we will ever make use of this screen share app. The way it is currently supposed to work isn't any better than a regular web browser, and I don't think we will ever modify WebRTC to make it any better than a web browser.
>
> This includes a placeholder to not break protocol.
> Tested on Linux.

Closes #435

### CODE REVIEW

**Comment by daleglass** [comment]
@HifiExperiments I incorporated your review comments into the last commit, please take a look!

**Comment by ksuprynowicz** [comment]
Windows build is failing for me with an unrecognized symbol:
```
image.lib(OpenEXRReader.obj) : error LNK2001: nierozpoznany symbol zewnętrzny imath_half_to_float_table [C:\Users\ksupr\source\overte\overte_v8\cmake-build-relwithdebinfo-visual-studio\plugins\openvr\openvr.vcxproj]
C:\Users\ksupr\source\overte\overte_v8\cmake-build-relwithdebinfo-visual-studio\plugins\openvr\RelWithDebInfo\openvr.dll : fatal error LNK1120: liczba nierozpoznanych elementów zewnętrznych: 1 
```

**Comment by ksuprynowicz** [comment]
Interface builds now :)

**Review by HifiExperiments — COMMENTED** [review]
I would suggest undoing the changes in the following files and moving them to a separate PR against the protocol_changes branch:
- EntityItemProperties.cpp/.h
- EntityPropertyFlags.h (just delete the prop entirely)
- ZoneEntityItem.cpp/.h (remove the ignoreUint32 thing)
- PacketHeaders.h (no need to rename the old version, just add a new version at the end)

with the `ignoreUint32` hack, this *might* not crash, but it's not worth the complexity/risk imo.

**Comment by HifiExperiments** [comment]
hope you don't mind but I took the opportunity to rebase this once again and really remove the property and bump the protocol (on the protocol_changes branch): https://github.com/overte-org/overte/pull/1165

**Pull request closed without merging**
