### PR TITLE
Japanese language support (and other IME probably)

### PR DESCRIPTION
**Pull request by ksuprynowicz**
For now it works in Desktop mode, not tested in VR.

### CODE REVIEW

**Comment by iamgreaser** [comment]
Confirmed that this also works with Korean using fcitx5 + hangul, at least for chat boxes.

However, there is a glitch to resolve: The window with the IME suggestions in it tends to be placed in a weird spot above the top of the screen around the centre. The ideal location for it is whereever the text is (typically just below the right-hand side of the last character), but failing that, a fixed location where it's guaranteed to be fully on-screen would work (maybe in the top-left of the display area?).

**Comment by ksuprynowicz** [comment]
Thanks! I was stuck with that part to be honest and I'm not sure how to do this. Advice and help would be really welcome.

**Comment by rassi0429** [comment]
I have some information about Qt in C++, but I think that when the argument of the inputMethodQuery function is Qt::ImCursorRectangle, returning QRect will change the coordinates of IME

In 3D, perhaps a projection into 2D is necessary, which may temporarily force the upper left corner.

```c

// OffscreenUi...?
QVariant GLWidget::inputMethodQuery(Qt::InputMethodQuery q) const 
{
	if (q == Qt::ImCursorRectangle) {
		int x =0;
		int y = 0;
                // or some calcuration
		return QRect(x, y, 1, 1);
	}
	return GLWidget::inputMethodQuery(q);
} 

```

**Comment by ksuprynowicz** [comment]
Thanks!
This function in libraries/ui/src/OffscreenUi.cpp maps coordinates to web entity:
```
            QMouseEvent* mouseEvent = static_cast<QMouseEvent*>(event);
            QPointF transformedPos = mapToVirtualScreen(mouseEvent->localPos());
            // FIXME: touch events are always being accepted.  Use mouse events on the OffScreenUi for now, and investigate properly switching to touch events
            // (using handlePointerEvent) later
            QMouseEvent mappedEvent(mouseEvent->type(), transformedPos, mouseEvent->screenPos(), mouseEvent->button(), mouseEvent->buttons(), mouseEvent->modifiers());
            mappedEvent.ignore();
            if (QCoreApplication::sendEvent(getWindow(), &mappedEvent)) {
                return mappedEvent.isAccepted();
            }
```
So it would probably be something similar but in reverse.

**Comment by ksuprynowicz** [comment]
For now I set position of IME popup to upper left part of the window. I'm kinda stuck on how to make it show up on needed position, so help is very welcome.

**Comment by JulianGro** [comment]
Testing build rehosted: https://public.overte.org/build/overte/testing/2023_05_27/Overte-PR431-f783a80.exe (since you apparently need to login on GitHub to download it from the workflow.

**Review by JulianGro — APPROVED** [review]

**Pull request merged**
