### PR TITLE
VR Keyboard: visual enhancement

### PR DESCRIPTION
**Pull request by AleziaKurdis**
This PR sets in grey the keys that are functional versus the key that generate content (in white)
it changes also the backspace for a more standard symbol.
It sets the key to close the keyboard in red and the Enter in green.

(This is to be tested first, I don't compile)

### CODE REVIEW

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-ab28c0f.tar.gz
 - https://public.overte.org/build/overte/PR147/Overte-PR147-ab28c0f.sh
 - https://public.overte.org/build/overte/PR147/Overte-PR147-ab28c0f.tar.Z

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-ab28c0f.dmg

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-ab28c0f.sh
 - https://public.overte.org/build/overte/PR147/Overte-PR147-ab28c0f.tar.Z
 - https://public.overte.org/build/overte/PR147/Overte-PR147-ab28c0f.tar.gz

**windows-2019, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-ab28c0f.exe

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-2441d42.tar.gz
 - https://public.overte.org/build/overte/PR147/Overte-PR147-2441d42.sh
 - https://public.overte.org/build/overte/PR147/Overte-PR147-2441d42.tar.Z

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-2441d42.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-2441d42.tar.Z
 - https://public.overte.org/build/overte/PR147/Overte-PR147-2441d42.sh
 - https://public.overte.org/build/overte/PR147/Overte-PR147-2441d42.tar.gz

**windows-2019, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-2441d42.exe

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-e6483dd.dmg

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-e6483dd.tar.gz
 - https://public.overte.org/build/overte/PR147/Overte-PR147-e6483dd.sh
 - https://public.overte.org/build/overte/PR147/Overte-PR147-e6483dd.tar.Z

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-e6483dd.tar.gz
 - https://public.overte.org/build/overte/PR147/Overte-PR147-e6483dd.tar.Z
 - https://public.overte.org/build/overte/PR147/Overte-PR147-e6483dd.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-e6483dd.exe

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-9cfe53b.tar.Z
 - https://public.overte.org/build/overte/PR147/Overte-PR147-9cfe53b.sh
 - https://public.overte.org/build/overte/PR147/Overte-PR147-9cfe53b.tar.gz

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-9cfe53b.tar.gz
 - https://public.overte.org/build/overte/PR147/Overte-PR147-9cfe53b.tar.Z
 - https://public.overte.org/build/overte/PR147/Overte-PR147-9cfe53b.sh

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-9cfe53b.dmg

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**windows-2019, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-9cfe53b.exe

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-0881274.tar.gz
 - https://public.overte.org/build/overte/PR147/Overte-PR147-0881274.tar.Z
 - https://public.overte.org/build/overte/PR147/Overte-PR147-0881274.sh

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-0881274.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-0881274.sh
 - https://public.overte.org/build/overte/PR147/Overte-PR147-0881274.tar.gz
 - https://public.overte.org/build/overte/PR147/Overte-PR147-0881274.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR147/Overte-PR147-0881274.exe

**Comment by AleziaKurdis** [comment]
Voilà.

image

**Review by ksuprynowicz — APPROVED** [review]

**Comment by ksuprynowicz** [comment]
It looks much nicer this way :)

**Pull request merged**
