### PR TITLE
Unlit Shapes

### LINKED ISSUE #901: Add option to render shapes as unlit
Add an entity property to shape entities that selects if it should use the PBR or unlit shader path, probably a Boolean "unlit" property
The create app should also have a checkbox to enable this.

### PR DESCRIPTION
**Pull request by HifiExperiments**
closes #901

### CODE REVIEW

**Comment by ksuprynowicz** [comment]
I tested it and almost everything works fine, except after shutting the client down and then starting again, Create App will show that unlit is unchecked, even though it's enabled:
image

**Comment by HifiExperiments** [comment]
@ksuprynowicz fixed this one too!  this ended up being an entirely different issue on the create side, seemingly because multiple entities have "unlit" properties now 🤷

**Comment by ksuprynowicz** [comment]
Everything works well now here too :)

**Comment by HifiExperiments** [comment]
ah!!  I got trigger happy and merged before CR.  @ksuprynowicz at your leisure, if you have any requested changes, I can make them in a separate PR, my apologies.  thanks so much for testing!

**Pull request merged**
