### PR TITLE
Add Docker server Github Actions builds

### PR DESCRIPTION
**Pull request by JulianGro**
This PR adds initial Overte server builds for Docker.

The Docker images can be directly imported without prior decompression:
```bash
docker image import overte-server-ab234cf553389d079b2fd46a68b95b3ea7f096be-11-amd64.tar.xz
```
To run the imported image, check the the image id:
```bash
docker images
```
And then start it using the image id:
```bash
docker run --publish-all 181d43f32e4a
```

### CODE REVIEW

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR105/Overte-PR105-42bf06a.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR105/Overte-PR105-42bf06a.exe

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR105/Overte-PR105-b3bb5bd.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR105/Overte-PR105-b3bb5bd.exe

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR105/Overte-PR105-b4c9bb4.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR105/Overte-PR105-b4c9bb4.exe

**Comment by JulianGro** [comment]
Little update on this:
The GitHub Actions uploader cannot deal with this.
Rather than rewriting the uploader I have been trying WoodpeckerCI as a replacement to GitHub Actions for Linux server builds.
Unfortunately it is still too unstable to production use. Their next release is going to be version 1.0.0 which is what we should wait for. The current "stable" release doesn't have all features we need, and the "next" version (which is automatic master builds) is far too unstable.

I will probably do Docker server builds manually for releases and release candidates only until WoodpeckerCI is stable enough.

**Pull request closed without merging**
