### PR TITLE
Ability to smooth model animations

### LINKED ISSUE #317: Add animation frame interpolation
This will allow for smaller and smoother looking animations, especially on very slow moving things. 
If you just reduce the playback rate to something like 5 fps it look very choppy so you have to make long animations (keyed at every single frame no less) and play them at 30 or more fps. Implementing frame interpolation solves this.

I vaguely recall Tivoli having done this, but I can't find any reference to it in the Tivolicloud repo issues.

### PR DESCRIPTION
**Pull request by HifiExperiments**
Closes #317 

A new Model Entity property, `animation.smoothFrames`, to control whether we linearly interpolate between animation frames.  It's true by default, but older content backups will default to false to maintain old behavior.

## Funding

This project is funded through [NGI0 Entrust](https://nlnet.nl/entrust), a fund established by [NLnet](https://nlnet.nl) with financial support from the European Commission's [Next Generation Internet](https://ngi.eu) program. Learn more at the [NLnet project page](https://nlnet.nl/project/Overte).

[NLnet foundation logo](https://nlnet.nl)
[NGI Zero Logo](https://nlnet.nl/entrust)

### CODE REVIEW

**Comment by vegaslon** [comment]
I have tested this on windows and can not see any difference in animation rendering, Everything appears to be in proper order and does what I would expect it to do.

**Comment by HifiExperiments** [comment]
@vegaslon to clarify, when you say "can not see any difference in animation rendering," you mean when the property is false?  and then when it's true, you see it working as expected?

**Comment by vegaslon** [comment]
yes that is correct, Works great with setting false or true it is doing what I would expect it to do.

**Comment by HifiExperiments** [comment]
@vegaslon sweet, thank you for testing!

**Review by ksuprynowicz — APPROVED** [review]
Everything looks fine :)

**Comment by HifiExperiments** [comment]
@ksuprynowicz thank you!!

**Pull request merged**
