### PR TITLE
Reworked TAA PR by HifiExperiments

### PR DESCRIPTION
**Pull request by ksuprynowicz**
This one needs a lot of testing both in desktop mode and VR to make sure nothing got broken.
TAA quality is a lot nicet than in main branch.

### CODE REVIEW

**Comment by ksuprynowicz** [comment]
It looks like I broke antialiasing mode toggle while rebasing

**Comment by ksuprynowicz** [comment]
It looks like against skybox only top and right edge of the contour is antialiased properly.
image

**Comment by ksuprynowicz** [comment]
With this version some ghosting occurs when avatar is moving. I wonder how difficult it would be to add armature-related movement to velocity buffer?

**Comment by ksuprynowicz** [comment]
Sadly it also breaks bloom. Black square with four small white squares often appears in places where bloom occurs.
image

**Comment by HifiExperiments** [comment]
> With this version some ghosting occurs when avatar is moving. I wonder how difficult it would be to add armature-related movement to velocity buffer?

yeah, the velocity buffer currently just uses the entity transform to calculate velocity so this breaks for skinned meshes.  we'd need all information necessary to calculate skinning for the previous frame.  the key on the shader side is this block here: https://github.com/overte-org/overte/blob/6e3586b2366f0f6b51460622342093e763993443/libraries/render-utils/src/model.slv#L63

we'd need an `evalPrevMeshDeformer` that does the same general thing but calculates `prevPositionMS` using the previous frame's buffers and uses that to get `_prevPositionCS` (instead of transformModelToWorldEyeClipPosAndPrevClipPos)

shouldn't be *that* hard but I forget how the cluster buffers work on the c++ side.  probably need two and then ping pong between them

**Comment by HifiExperiments** [comment]
> Sadly it also breaks bloom. Black square with four small white squares often appears in places where bloom occurs. image

hmmm I don't remember this being an issue all those years ago...maybe renderdoc would help if you could catch this?

**Comment by HifiExperiments** [comment]
closing in favor of #1213

**Pull request closed without merging**
