### PR TITLE
Add mouse look script

### PR DESCRIPTION
**Pull request by rampa3**
Adds WIP implementation of mouse look script. Is an early implementation of solution for https://github.com/overte-org/overte/issues/85.

Current issues with the script:
- it is possible to leave chat overlay window (and any other overlay windows) open when hiding tablet, when in use on desktop mode, which causes a softlock, where keyboard controls the overlay, while mouse is being captured for camera look (Low priority – using tablet UI on desktop is not officially supported.)
- ~~the various conditions for temporarily pausing mouse look are not linked together – need to find an elegant way to link them~~ (Was solved, including stacking of tablet up and away conditions. Also added detection of VR being used to disable the script when HMD is in use.)
- ~~elegant way to get focus state of the interface window to pause mouse look and release mouse on unfocus~~ (Works without API.)
- ~~mouse sensitivity slider will be needed – default mouse look sensitivity is too high~~ (Already exists, I just looked wrong.)
- ~~a setting is needed for mouse look is needed for final release~~ (Done in commit https://github.com/overte-org/overte/pull/449/commits/b01300c4cefbfaa8717987d27f82332c5b7e6492.)
- user might not see script status after window resizing because of https://github.com/overte-org/overte/issues/470 (Not urgent, but inconvenient.)

### CODE REVIEW

**Comment by vegaslon** [comment]
there is a event for when the mouse is captured you can make it cleaner with this https://apidocs.overte.org/Camera.html#.captureMouseChanged

**Review by ksuprynowicz — APPROVED** [review]
Everything looks fine. If someone would like to review my part of this commit (C++ side) it would be very welcome too.

**Comment by ksuprynowicz** [comment]
Everything works perfectly in desktop mode, but it in VR mode it doesn't disable mouse look

**Comment by ksuprynowicz** [comment]
After the newest change switching off mouse look when getting into VR mode works perfectly too :)
I think this is ready to merge unless someone else would like to add a second review.

**Comment by vegaslon** [comment]
What happens when you turn on the mouse look setting while in vr?

**Comment by ksuprynowicz** [comment]
> What happens when you turn on the mouse look setting while in vr?

Earlier things would get very glitchy then, but after newest commit it's just not allowed anymore.

**Comment by rampa3** [comment]
> After the newest change switching off mouse look when getting into VR mode works perfectly too :) I think this is ready to merge unless someone else would like to add a second review.

Maybe test if you like how the temporary pause trough m key works before merging – at the moment, there is an event that resets the mouse look to ON. If you don't like it, we should remove it before shipping. Particularly, going away and coming back resets the temporary pause at the moment. Unless there is another additional one I forgot, it should be the only one.

**Comment by ksuprynowicz** [comment]
I think that current behavior is very reasonable in my opinion

**Comment by rampa3** [comment]
> I think that current behavior is very reasonable in my opinion

OK, I think we can go for merge then.

Btw, I have updated the list at the top to list current state – overlay detection being on low priority, and misbehaving announcements on resize being inconvenice, but not a show stopper. Also I updated that the setting was added.

Shoud I maybe put in the overlay detection as an issue we could mark as low priority, since it is not officialy supported way of having the UI on desktop, so we can track it?

**Comment by ksuprynowicz** [comment]
Yes, we should either create such issue, or just add a TODO in the code.

**Comment by vegaslon** [comment]
As long as it plays nice going in and out of VR while turning on and off the settings and pushing all the buttons

**Comment by vegaslon** [comment]
Mouse look can not be activated if you start overte in vr mode. Have to click the setting and restart the interface

**Comment by ksuprynowicz** [comment]
> Mouse look can not be activated if you start overte in vr mode. Have to click the setting and restart the interface

Does this also happen when the setting is already set on start or does it only happen is it was not set before?

**Comment by vegaslon** [comment]
not set before, also I am sure know this but it is impossible to login while in mouse look mode. If you go to away and login it will bring you out of away mode in an unrecoverable state with the web window in control. Can not go into away again at that point. only way out out of it is force killing client or putting on a vr headset.

**Comment by ksuprynowicz** [comment]
> not set before, also I am sure know this but it is impossible to login while in mouse look mode. If you go to away and login it will bring you out of away mode in an unrecoverable state with the web window in control. Can not go into away again at that point. only way out out of it is force killing client or putting on a vr headset.

Thank you for finding this issue! We will need to fix it before merging. Maybe mouse look should be toggled off after away? Or maybe we should always toggle it off when overlay window is gaining focus?

**Comment by rampa3** [comment]
> > not set before, also I am sure know this but it is impossible to login while in mouse look mode. If you go to away and login it will bring you out of away mode in an unrecoverable state with the web window in control. Can not go into away again at that point. only way out out of it is force killing client or putting on a vr headset.
> 
> Thank you for finding this issue! We will need to fix it before merging. Maybe mouse look should be toggled off after away? Or maybe we should always toggle it off when overlay window is gaining focus?

Dang it! So overlay detection is not as small deal as I thought it is... So what now? There are no API endpoints to check globally for overlays. We can only interact with exact window if I read the docs right.

**Comment by ksuprynowicz** [comment]
> Dang it! So overlay detection is not as small deal as I thought it is... What now? There are no API endpoints to check globally for overlays. We can only interact with exact window if I read the docs right. (I forgot everything is overlay unless you use the desktop tablet... 😅)

I think the best way would be adding a signal that happens if any overlay gains focus. Then we could use that signal.
I will add it next weekend if all goes well. Please remind me if I forget.

**Pull request closed without merging**
