### PR TITLE
Remove legally problematic texture

### PR DESCRIPTION
**Pull request by JulianGro**
Fixes https://github.com/overte-org/overte/issues/213

This PR removes a legally problematic texture from the script archive. Other textures do not appear to be from the same source, and appear to be original. Google Lens didn't find any matches to the other textures, while it did immediately find the problematic leather texture. Looking at the hifi content archive suggests that the `texture_accreditation.txt` was added together with that leather texture.

### CODE REVIEW

**Review by daleglass — APPROVED** [review]
Perhaps let's add a README.md or something in case this needs reviving?

Eg,

Leather0100_2_L.jpg and Leather0100-bump.jpg were removed for licensing concerns.  The contents were a dark brown leather grain texture and the bump map.

**Comment by daleglass** [comment]
Also, out of curiosity, I tried generating a texture with DALLE3.  Seems decent enough at least temporarily. Any thoughts on that?

**Comment by ksuprynowicz** [comment]
I'd prefer not including ML generated images in main repo until legal situation around their use is clear.

**Comment by daleglass** [comment]
Fair enough!

**Comment by JulianGro** [comment]
I don't think a README is very important, since I doubt that this will ever be revived. The code not finding "Leather(…).jpg" should be clue enough IMO.

**Pull request merged**
