### PR TITLE
Quick workaround for Nvidia driver bug

### PR DESCRIPTION
**Pull request by ksuprynowicz**
Already fixes polyline rendering, but laser pointers still don't show up.

### CODE REVIEW

**Comment by ksuprynowicz** [comment]
Should also fix Nvidia driver crash on Linux

**Comment by JulianGro** [comment]
Fixes the crash on startup on Ubuntu 22.04 with 525.60.11 proprietary directly from Nvidia.

**Comment by daleglass** [comment]
I'm a bit confused as to how this fixes the crash. Is it that `packDeferredFragmentUnlit` makes things crash somehow?

**Review by JulianGro — APPROVED** [review]
This looks a lot more of a permanent temporary solution now.

**Comment by ksuprynowicz** [comment]
I tested it on Windows and Linux (Debian Testing) so I think it's safe to merge

**Pull request merged**
