### PR TITLE
Web Entity wantsKeyboardFocus

### PR DESCRIPTION
**Pull request by HifiExperiments**
https://github.com/overte-org/overte/issues/692

### CODE REVIEW

**Comment by JulianGro** [comment]
This is a protocol break, right?

**Comment by gydence** [comment]
@JulianGro yep, this is targeting the protocol_change branch, which also has mirrors and tags.  several of the other PRs I’m working on will also be protocol bumps, and then we can merge this branch to master whenever we decide to do the next RC

**Comment by JulianGro** [comment]
The server tag should make it build some server packages that can be used for testing.

**Review by daleglass — APPROVED** [review]

**Comment by ksuprynowicz** [comment]
I just tested it, and I noticed two problems. The Wants Keyboard Focus property seems to reset to enabled soon after disabling it. Also Focus Highlight and Wants Keyboard Focus seem to be coupled in some way and sometimes I can't disable Wants Keyboard Focus in Create App at all.

**Comment by HifiExperiments** [comment]
@ksuprynowicz ugh I'm sorry, I had a copy-paste error that would affect this in non-serverless.  should be fixed now

**Review by JulianGro — APPROVED** [review]
I haven't been able to mess with the models.json.gz without the server complaining, but everything seems to work fine.
If `wantsKeyboardFocus` is not defined, it acts as if it is `true`, which should keep legacy behaviour. When disabling it in the Create app, it creates the relevant entry with `false`.
Restarting the server, proofs that the setting persists.
All of this was tested on a localhost server.

I did however run into https://github.com/overte-org/overte/issues/846, which I don't think would be related to this PR.

**Comment by ksuprynowicz** [comment]
I wonder why it wouldn't work correctly when I tested it? Setting seemed to reset to true on its own and sometimes even couldn't be set to false.

**Comment by JulianGro** [comment]
@ksuprynowicz, on my end, it takes a while for the changes to actually save. The way I worked around this is by leaving the server running for 10 minutes and then restarting it. If I restart it closely after making a change, said change will disappear.

**Comment by ksuprynowicz** [comment]
The weird thing though was that I was not restarting the server at all. The setting was resetting to true while server was running, and on the same client session without leaving and rejoining. It worked for a few seconds and then would spontaneously revert, and on some occassions was just stuck on true without possibility to switch it to false.

**Comment by JulianGro** [comment]
@ksuprynowicz, I didn't notice this before, but it looks like HifiExperiments tried fixing this exact issue in 7941c9e.
Did you retry since then?

**Comment by ksuprynowicz** [comment]
Thanks! I missed his message
I will build and test it again in a moment :)

**Comment by ksuprynowicz** [comment]
I tested again and it works perfectly now :)
I think this PR is ready for merging into protocol change branch

**Pull request merged**
