### PR TITLE
Change minimum angular velocity to a lower one

### PR DESCRIPTION
**Pull request by ksuprynowicz**
Should fix https://github.com/overte-org/overte/issues/1170
Needs testing with both client and server on this PR.

### CODE REVIEW

**Comment by ksuprynowicz** [comment]
There's still something setting the angular velocity to 0 when it's below certain threshold. I have trouble figuring what though. I tried lowering ACTIVATION_ANGULAR_VELOCITY_DELTA too but it didn't help.

**Comment by HifiExperiments** [comment]
I don’t remember all the details but this could be due to how we send quaternions over the network?  I vaguely remember that they are compressed in a way that can lose some precision

**Comment by ksuprynowicz** [comment]
I'm giving up on this for now. Somehow after being set from script engine angular velocity gets set to 0 and I'm not able to find where. In `ObjectMotionState::handleEasyChanges` already wrong value (0,0,0) is passed to Bullet Physics.
The issue happens even in serverless, so it doesn't seem server-related.

**Comment by HifiExperiments** [comment]
hm I also see this:
```
        const float MIN_KINEMATIC_ANGULAR_SPEED_SQUARED =
            KINEMATIC_ANGULAR_SPEED_THRESHOLD * KINEMATIC_ANGULAR_SPEED_THRESHOLD;
        if (glm::length2(angularVelocity) < MIN_KINEMATIC_ANGULAR_SPEED_SQUARED) {
            angularVelocity = Vectors::ZERO;
        }
```
in EntityItem::stepKinematicMotion.  and:
```
const float KINEMATIC_ANGULAR_SPEED_THRESHOLD = 0.008f;  // ~0.5 deg/sec
```

**Comment by ksuprynowicz** [comment]
@HifiExperiments Thank you! This fixes the issue :)

**Comment by ksuprynowicz** [comment]
I tested it and all works well so I think it's ready for review and merging.

**Review by HifiExperiments — APPROVED** [review]
(I just rebased this to resolve the conflicts with the changes from protocol_changes)

do we think there's any downside to lowering these values?  like maybe we're simulating more things for slightly longer...but it shouldn't really matter?

**Pull request merged**
