### PR TITLE
Create audio tests for AudioClient and codecs

### PR DESCRIPTION
**Pull request by daleglass**
This is a start for audio testing and helping with debugging audio PRs.

Might help with debugging #171

### CODE REVIEW

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR177/Overte-PR177-fe51a9f.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR177/Overte-PR177-fe51a9f.exe

**Review by akamicah — APPROVED** [review]
Looks good to me

**Comment by daleglass** [comment]
To test, build with `cmake  -DBUILD_TESTS=ON`, and then `make all-tests`

This will create `tests/audio` in the output dir.

**Comment by JulianGro** [comment]
Appears to be working.
Well, or rather it runs into the same issue as Interface on my system.
```
juliangro@x299-desktop:~/git/overte/build/tests$ ./audio/audio-AudioTests
********* Start testing of AudioTests *********
Config: Using QtTest library 5.15.4, Qt 5.15.4 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 12.1.0), debian unknown
QDEBUG : AudioTests::initTestCase() hifi.networking: Asynchronously looking up IP address for hostname "stun1.l.google.com" - lookup ID is 1
QDEBUG : AudioTests::initTestCase() hifi.networking: Changed socket "send" buffer size from 212992 to 425984 bytes
QDEBUG : AudioTests::initTestCase() hifi.networking: Changed socket "receive" buffer size from 212992 to 425984 bytes
QDEBUG : AudioTests::initTestCase() hifi.networking: NodeList UDP socket is listening on 10000
QDEBUG : AudioTests::initTestCase() hifi.networking: Did not change socket "send" buffer size from 1048576 since it is larger than desired size of 1048576
QDEBUG : AudioTests::initTestCase() hifi.networking: Did not change socket "receive" buffer size from 1048576 since it is larger than desired size of 1048576
QINFO  : AudioTests::initTestCase() hifi.networking: Local socket is "UDP ""192.168.1.10":10000
QWARN  : AudioTests::initTestCase() DependencyManager::get(): No instance available for 14AddressManager
QWARN  : AudioTests::initTestCase() QObject::connect(QTimer, Unknown): invalid nullptr parameter
QWARN  : AudioTests::initTestCase() DependencyManager::get(): No instance available for 14AddressManager
QWARN  : AudioTests::initTestCase() QObject::connect(AddressManager, DomainHandler): invalid nullptr parameter
QWARN  : AudioTests::initTestCase() QObject::connect(AddressManager, DomainHandler): invalid nullptr parameter
QWARN  : AudioTests::initTestCase() QObject::connect(AddressManager, NodeList): invalid nullptr parameter
QWARN  : AudioTests::initTestCase() DependencyManager::get(): No instance available for 8NodeList
QWARN  : AudioTests::initTestCase() DependencyManager::get(): No instance available for 14AccountManager
QWARN  : AudioTests::initTestCase() QObject::connect(AccountManager, NodeList): invalid nullptr parameter
QWARN  : AudioTests::initTestCase() QObject::connect(AccountManager, NodeList): invalid nullptr parameter
QWARN  : AudioTests::initTestCase() QObject::connect(AccountManager, NodeList): invalid nullptr parameter
QWARN  : AudioTests::initTestCase() DependencyManager::get(): No instance available for 20DomainAccountManager
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 2 (DomainList)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 3 (Ping)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 4 (PingReply)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 39 (ICEPing)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 21 (DomainServerAddedNode)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 46 (DomainServerConnectionToken)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 16 (DomainConnectionDenied)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 48 (DomainSettings)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 22 (ICEServerPeerInformation)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 32 (DomainServerRequireDTLS)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 40 (ICEPingReply)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 20 (DomainServerPathResponse)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 56 (DomainServerRemovedNode)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 71 (UsernameFromIDReply)
QWARN  : AudioTests::initTestCase() Setting::Interface::init() for key "audioOutputBufferFrames" - Manager not yet created. Settings persistence disabled.
(audio_processing_impl.cc:272): Injected APM submodules:
Echo control factory: 0
Echo detector: 0
Capture analyzer: 0
Capture post processor: 0
Render pre processor: 0
(audio_processing_impl.cc:526): AudioProcessing::ApplyConfig: AudioProcessing::Config{ pipeline: {maximum_internal_processing_rate: 48000, multi_channel_render: 0, , multi_channel_capture: 0}, pre_amplifier: { enabled: 0, fixed_gain_factor: 1 }, high_pass_filter: { enabled: 0 }, echo_canceller: { enabled: 1, mobile_mode: 0, enforce_high_pass_filtering: 1 }, noise_suppression: { enabled: 0, level: Moderate }, transient_suppression: { enabled: 0 }, voice_detection: { enabled: 0 }, gain_controller1: { enabled: 0, mode: AdaptiveAnalog, target_level_dbfs: 3, compression_gain_db: 9, enable_limiter: 1, analog_level_minimum: 0, analog_level_maximum: 255 }, gain_controller2: { enabled: 0, fixed_digital: { gain_db: 0 }, adaptive_digital: { enabled: 0, level_estimator: Rms, use_saturation_protector: 1, extra_saturation_margin_db: 2 } }, residual_echo_detector: { enabled: 1 }, level_estimation: { enabled: 0 } }
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 18 (AudioStreamStats)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 36 (AudioEnvironment)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 12 (SilentAudioFrame)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 8 (MixedAudio)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 28 (NoisyMute)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 17 (MuteEnvironment)
QDEBUG : AudioTests::initTestCase() hifi.networking: Registering a packet listener for packet list type 65 (SelectedAudioFormat)
PASS   : AudioTests::initTestCase()
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: switchInputToAudioDevice _inputDeviceInfo: [ "" : "" -- inputDeviceInfo: "" : "" ]
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: Audio input device is not available, using dummy input.
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: The format to be used for audio input is QAudioFormat(24000Hz, 16bit, channelCount=1, sampleType=SignedInt, byteOrder=LittleEndian, codec="audio/pcm")
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: No resampling required for audio input to match desired network format.
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: Noise gate created with 1 channels.
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: getAvailableDevices Default device not found in list no alternative selection available
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: switchOutputToAudioDevice _outputdeviceInfo: [ "" : "" -- outputDeviceInfo: "" : "" ]
QDEBUG : AudioTests::listAudioDevices() hifi.networking: QHostInfo lookup result for "stun1.l.google.com" with lookup ID 1 is "64.233.163.127"
QDEBUG : AudioTests::listAudioDevices() hifi.networking: Sending initial stun request to stun1.l.google.com
QDEBUG : AudioTests::listAudioDevices() hifi.networking: New public socket received from STUN server is 176.199.104.17:10000 (was :0)
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: getAvailableDevices Default device not found in list no alternative selection available
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: getAvailableDevices Default device not found in list no alternative selection available
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: getAvailableDevices Default device not found in list no alternative selection available
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: getAvailableDevices Default device not found in list no alternative selection available
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: getAvailableDevices Default device not found in list no alternative selection available
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: getAvailableDevices Default device not found in list no alternative selection available
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: getAvailableDevices Default device not found in list no alternative selection available
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: getAvailableDevices Default device not found in list no alternative selection available
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: getAvailableDevices Default device not found in list no alternative selection available
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: getAvailableDevices Default device not found in list no alternative selection available
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: getAvailableDevices Default device not found in list no alternative selection available
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: getAvailableDevices Default device not found in list no alternative selection available
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: getAvailableDevices Default device not found in list no alternative selection available
QDEBUG : AudioTests::listAudioDevices() hifi.audioclient: getAvailableDevices Default device not found in list no alternative selection available
FAIL!  : AudioTests::listAudioDevices() 'spy.count() > 0' returned FALSE. ()
   Loc: [/home/juliangro/git/overte/tests/audio/src/AudioTests.cpp(69)]
PASS   : AudioTests::cleanupTestCase()
Totals: 2 passed, 1 failed, 0 skipped, 0 blacklisted, 14279ms
********* Finished testing of AudioTests *********
juliangro@x299-desktop:~/git/overte/build/tests$
```
```       
juliangro@x299-desktop:~/git/overte/build/tests$ ./audio/audio-CodecTests
********* Start testing of CodecTests *********
Config: Using QtTest library 5.15.4, Qt 5.15.4 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 12.1.0), debian unknown
QDEBUG : CodecTests::initTestCase() Our directory is QDir( "/home/juliangro/git/overte/build/tests/audio" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
QDEBUG : CodecTests::initTestCase() Interface plugins are at QDir( "/home/juliangro/git/overte/build" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
QDEBUG : CodecTests::initTestCase() Our plugins are at "/home/juliangro/git/overte/build/tests/audio/plugins"
PASS   : CodecTests::initTestCase()
QINFO  : CodecTests::loadCodecs() Loading runtime plugins from  "/home/juliangro/git/overte/build/tests/audio/plugins/"
QWARN  : CodecTests::loadCodecs() Setting::Interface::init() for key "private/enableScriptingPlugins" - Manager not yet created. Settings persistence disabled.
QDEBUG : CodecTests::loadCodecs() hifi.plugins: Attempting plugin CMakeCXXCompiler.cmake
QWARN  : CodecTests::loadCodecs() hifi.plugins: Plugin CMakeCXXCompiler.cmake interface version doesn't match, not loading: 0 doesn't match 1
QDEBUG : CodecTests::loadCodecs() hifi.plugins: Attempting plugin CMakeCache.txt
QWARN  : CodecTests::loadCodecs() hifi.plugins: Plugin CMakeCache.txt interface version doesn't match, not loading: 0 doesn't match 1
QDEBUG : CodecTests::loadCodecs() hifi.plugins: Attempting plugin CPackConfig.cmake
QWARN  : CodecTests::loadCodecs() hifi.plugins: Plugin CPackConfig.cmake interface version doesn't match, not loading: 0 doesn't match 1
QDEBUG : CodecTests::loadCodecs() hifi.plugins: Attempting plugin CPackCustomProperties.cmake
QWARN  : CodecTests::loadCodecs() hifi.plugins: Plugin CPackCustomProperties.cmake interface version doesn't match, not loading: 0 doesn't match 1
QDEBUG : CodecTests::loadCodecs() hifi.plugins: Attempting plugin CPackSourceConfig.cmake
QWARN  : CodecTests::loadCodecs() hifi.plugins: Plugin CPackSourceConfig.cmake interface version doesn't match, not loading: 0 doesn't match 1
QDEBUG : CodecTests::loadCodecs() hifi.plugins: Attempting plugin CTestTestfile.cmake
QWARN  : CodecTests::loadCodecs() hifi.plugins: Plugin CTestTestfile.cmake interface version doesn't match, not loading: 0 doesn't match 1
QDEBUG : CodecTests::loadCodecs() hifi.plugins: Attempting plugin DartConfiguration.tcl
QWARN  : CodecTests::loadCodecs() hifi.plugins: Plugin DartConfiguration.tcl interface version doesn't match, not loading: 0 doesn't match 1
QDEBUG : CodecTests::loadCodecs() hifi.plugins: Attempting plugin Makefile
QWARN  : CodecTests::loadCodecs() hifi.plugins: Plugin Makefile interface version doesn't match, not loading: 0 doesn't match 1
QDEBUG : CodecTests::loadCodecs() hifi.plugins: Attempting plugin cmake_install.cmake
QWARN  : CodecTests::loadCodecs() hifi.plugins: Plugin cmake_install.cmake interface version doesn't match, not loading: 0 doesn't match 1
QDEBUG : CodecTests::loadCodecs() hifi.plugins: Attempting plugin vcpkg.cmake
QWARN  : CodecTests::loadCodecs() hifi.plugins: Plugin vcpkg.cmake interface version doesn't match, not loading: 0 doesn't match 1
FAIL!  : CodecTests::loadCodecs() 'codecPlugins.size() > 0' returned FALSE. ()
   Loc: [/home/juliangro/git/overte/tests/audio/src/CodecTests.cpp(49)]
FAIL!  : CodecTests::testEncoders() 'codecPlugins.size() > 0' returned FALSE. ()
   Loc: [/home/juliangro/git/overte/tests/audio/src/CodecTests.cpp(63)]
FAIL!  : CodecTests::testDecoders() 'codecPlugins.size() > 0' returned FALSE. ()
   Loc: [/home/juliangro/git/overte/tests/audio/src/CodecTests.cpp(89)]
PASS   : CodecTests::cleanupTestCase()
Totals: 2 passed, 3 failed, 0 skipped, 0 blacklisted, 11ms
********* Finished testing of CodecTests *********
juliangro@x299-desktop:~/git/overte/build/tests$ 
```

**Comment by daleglass** [comment]
Okay! Well, now the idea is that you have something much smaller to debug.

**Comment by daleglass** [comment]
For the second one it looks like something went wrong with finding the plugin directory. That part is a tad hacky, but I have plans for redoing the way that's handled in a future PR, so it didn't seem to make much sense to spend a lot of time on it

**Comment by JulianGro** [comment]
I assume it didn't build the plugins since I only built the tests without Interface or anything.

**Pull request merged**
