### PR TITLE
Fixed incorrect Script.require behavior

### PR DESCRIPTION
**Pull request by ksuprynowicz**
This needs a lot of testing, since pretty much anything using Script.require can be broken by changing its behavior.

### CODE REVIEW

**Comment by daleglass** [comment]
I ran this against the new test script I made (ScriptEngineNetworkedTests.cpp):

Here's how master performs (a few irrelevant lines removed):

```
QDEBUG : ScriptEngineNetworkedTests::testRequire() Printed message from engine "testRequire.js" :  "Value from A: 5"
QDEBUG : ScriptEngineNetworkedTests::testRequire() overte.scriptengine.script: [testRequire.js] Value from A: 5
QDEBUG : ScriptEngineNetworkedTests::testRequire() Printed message from engine "testRequire.js" :  "Value from B: 6"
QDEBUG : ScriptEngineNetworkedTests::testRequire() overte.scriptengine.script: [testRequire.js] Value from B: 6
QDEBUG : ScriptEngineNetworkedTests::testRequire() Printed message from engine "testRequire.js" :  "Done"
QDEBUG : ScriptEngineNetworkedTests::testRequire() overte.scriptengine.script: [testRequire.js] Done
QINFO  : ScriptEngineNetworkedTests::testRequire() Running state changed. Running =  true ; Stopped =  false ; Finished =  true
QDEBUG : ScriptEngineNetworkedTests::testRequire() overte.scriptengine: Waiting for finish
QINFO  : ScriptEngineNetworkedTests::testRequire() overte.scriptengine: [testRequire.js] Script Engine stopping:testRequire.js
QINFO  : ScriptEngineNetworkedTests::testRequire() Info message from engine "testRequire.js" :  "Script Engine stopping:testRequire.js"
QINFO  : ScriptEngineNetworkedTests::testRequire() Finished running script "testRequire.js"
QINFO  : ScriptEngineNetworkedTests::testRequire() Running state changed. Running =  false ; Stopped =  false ; Finished =  true
FAIL!  : ScriptEngineNetworkedTests::testRequire() 'printed[i] == expected[i]' returned FALSE. (Result 'Value from A: 5' didn't match expected 'Value from A: 6')
   Loc: [/home/vadim/git/vircadia/overte/tests/script-engine/src/ScriptEngineNetworkedTests.cpp(153)]
PASS   : ScriptEngineNetworkedTests::cleanupTestCase()
Totals: 2 passed, 1 failed, 0 skipped, 0 blacklisted, 64ms
********* Finished testing of ScriptEngineNetworkedTests *********
```


Here's after this PR:
```
QDEBUG : ScriptEngineNetworkedTests::testRequire() Printed message from engine "testRequire.js" :  "Value from A: 6"
QDEBUG : ScriptEngineNetworkedTests::testRequire() overte.scriptengine.script: [testRequire.js] Value from A: 6
QDEBUG : ScriptEngineNetworkedTests::testRequire() Printed message from engine "testRequire.js" :  "Value from B: 6"
QDEBUG : ScriptEngineNetworkedTests::testRequire() overte.scriptengine.script: [testRequire.js] Value from B: 6
QDEBUG : ScriptEngineNetworkedTests::testRequire() Printed message from engine "testRequire.js" :  "Done"
QDEBUG : ScriptEngineNetworkedTests::testRequire() overte.scriptengine.script: [testRequire.js] Done
QINFO  : ScriptEngineNetworkedTests::testRequire() Running state changed. Running =  true ; Stopped =  false ; Finished =  true
QDEBUG : ScriptEngineNetworkedTests::testRequire() overte.scriptengine: Waiting for finish
QINFO  : ScriptEngineNetworkedTests::testRequire() overte.scriptengine: [testRequire.js] Script Engine stopping:testRequire.js
QINFO  : ScriptEngineNetworkedTests::testRequire() Info message from engine "testRequire.js" :  "Script Engine stopping:testRequire.js"
QINFO  : ScriptEngineNetworkedTests::testRequire() Finished running script "testRequire.js"
QINFO  : ScriptEngineNetworkedTests::testRequire() Running state changed. Running =  false ; Stopped =  false ; Finished =  true
PASS   : ScriptEngineNetworkedTests::testRequire()
PASS   : ScriptEngineNetworkedTests::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 73ms
********* Finished testing of ScriptEngineNetworkedTests *********
```

Test now passes. The test only includes what was described in #702, there may be more things to test.

**Comment by ksuprynowicz** [comment]
This just needs a code review and testing now

**Comment by daleglass** [comment]
For the test, see above. This was made from #702

**Review by daleglass — APPROVED** [review]

**Comment by daleglass** [comment]
There's a bunch of other stuff here that may be good to look into:

https://nodejs.org/api/modules.html

**Pull request merged**
