### PR TITLE
possible fix for missing jsdoc

### PR DESCRIPTION
**Pull request by HifiExperiments**

### CODE REVIEW

**Comment by daleglass** [comment]
`.in` files look like something that's first pre-processed by something else to generate the real `.h`, so I believe a better fix would be to ensure jsdoc runs after that's done, and picks up the final, generated file

**Comment by HifiExperiments** [comment]
they’re processed by cmake, does jsdoc usually require running cmake?

**Comment by HifiExperiments** [comment]
it does not: https://github.com/overte-org/overte/blob/master/tools/jsdoc/README.md

an alternative fix would be to move the jsdoc to only be in actual .cpp/.h files, but that seems risky since other folks in the future could make the same mistake

**Review by ksuprynowicz — APPROVED** [review]
Everything looks good :)

**Comment by ksuprynowicz** [comment]
I tested it, and everything works properly, for example haze properties which are documented in .h.in file show up.

**Pull request merged**
