### PR TITLE
More app: New UI 2022.

### PR DESCRIPTION
**Pull request by AleziaKurdis**
Add a better search:

- You can now directly type to get the results,
- Search on Name (default) and Description (optional)

Get ride of the clunky pager for a scrollable list with a "Load More..." button every 20 entries.

Redesign the UI with the color that match other UI. (Dark theme)

Remove the useless hyperlink for the contribution (you can't expect using that window to contribute)
Instead it gives the indication to the repository.

172034399-7d9e71bb-3710-45af-a303-e636b03449a7

172034402-e1cc0231-1c30-4d51-815b-c5bc8ee3be26

**Note: There is another PR in community-apps repository that need to be merged with this one to keep the 2 version on sync.**

**Please test it carefully, because I have not tested it in Overte. (but all the url changes has been done.)**

### CODE REVIEW

**Comment by AleziaKurdis** [comment]
The othe PR in community app is:
https://github.com/overte-org/community-apps/pull/5

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR80/Overte-PR80-da38733.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR80/Overte-PR80-da38733.sh
 - https://public.overte.org/build/overte/PR80/Overte-PR80-da38733.tar.Z
 - https://public.overte.org/build/overte/PR80/Overte-PR80-da38733.tar.gz

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR80/Overte-PR80-da38733.sh
 - https://public.overte.org/build/overte/PR80/Overte-PR80-da38733.tar.Z
 - https://public.overte.org/build/overte/PR80/Overte-PR80-da38733.tar.gz

**windows-2019, full**
 - https://public.overte.org/build/overte/PR80/Overte-PR80-da38733.exe

**Review by ksuprynowicz — APPROVED** [review]
Thank you!
I've read the code and everything looks good in my opinion. Can you add the changes CtrLAltDavid from Vircadia requested? ("!=" needs to be "!==" in one place, and font related change)

**Comment by ksuprynowicz** [comment]
I tested it on Linux in desktop mode and everything works perfectly. Let me know if you tested it in VR on Windows. If so, it's ready to merge after changes CtrlAltDavid requested.

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR80/Overte-PR80-6a32982.sh
 - https://public.overte.org/build/overte/PR80/Overte-PR80-6a32982.tar.Z
 - https://public.overte.org/build/overte/PR80/Overte-PR80-6a32982.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR80/Overte-PR80-6a32982.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR80/Overte-PR80-6a32982.exe

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR80/Overte-PR80-6a32982.tar.gz
 - https://public.overte.org/build/overte/PR80/Overte-PR80-6a32982.sh
 - https://public.overte.org/build/overte/PR80/Overte-PR80-6a32982.tar.Z

**Comment by ksuprynowicz** [comment]
I tested it on Windows in VR too, and it works exactly like it should. I think that it's safe to merge at this point.

**Pull request merged**
