### PR TITLE
Fix Locker issue in RecordingScriptingInterface

### LINKED ISSUE #1005: Lock related warnings in RecordingScriptingInterface.cpp
```
/home/dale/git/overte/libraries/recording/src/recording/RecordingScriptingInterface.cpp:41:11: warning: unnecessary parentheses in declaration of ‘_mutex’ [-Wparentheses]
   41 |     Locker(_mutex);
      |           ^~~~~~~~
```

I'm a bit confused about what's going on here. Locker works out to `std::unique_lock<Mutex>;`

Shouldn't we be using `std::lock_guard guard(_mutex)` here?

### PR DESCRIPTION
**Pull request by HifiExperiments**
Fixes #1005, my bad for not noticing this

### CODE REVIEW

**Review by daleglass — APPROVED** [review]

**Review by ksuprynowicz — APPROVED** [review]

**Comment by ksuprynowicz** [comment]
Assignment client is deadlocking on this PR. I'm working on a fix right now.

**Comment by ksuprynowicz** [comment]
Interface is deadlocking too. It should be pretty easy to fix though.

**Comment by ksuprynowicz** [comment]
Oops... I had wrong project open in clion. I will post more test results in a moment.

**Comment by ksuprynowicz** [comment]
I'm getting a very weird assert on script thread:
```
__pthread_kill_implementation 0x00007ffff06a9e2c
AssetScriptingInterface::jsCallback AssetScriptingInterface.cpp:247
AssetScriptingInterface::jsCallback AssetScriptingInterface.cpp:263
operator() AssetScriptingInterface.cpp:104
<lambda#1>::operator()() const MiniPromises.h:204
MiniPromise::executeOnPromiseThread(std::function<…>, std::shared_ptr<…>) MiniPromises.h:66
Application::notify Application.cpp:4292
ScriptManager::run ScriptManager.cpp:1018
operator() ScriptManager.cpp:419
```

**Comment by ksuprynowicz** [comment]
I found cause of deadlocks in assignment client and I'm working on a fix.

**Comment by ksuprynowicz** [comment]
I have a fix :)
https://github.com/HifiExperiments/overte/pull/1/files

**Comment by ksuprynowicz** [comment]
The reason why the deadlock happened is that some recording API functions can have JS callback. If another recording API function gets called in callbacks, and it blocking-invokes itself on main thread, then deadlock will happen.

**Pull request merged**
