### PR TITLE
Create app: Material Data Assistant.

### PR DESCRIPTION
**Pull request by AleziaKurdis**
This PR add a "**Material Data Assistant**" to the UI of the Material Entity.
You can dynamically change the different Material properties using a new UI.
This is not replacing the current JSON editor, but it add another way to compose material without have to code a JSON using the documentation to know how it is working.

img1

img2

**Note: This is tool have some limitation.**
_(There are thing that Material allows that is not supported by this Assistant. There is still the JSON editor to do more advanced things)_

- The Assistant button will be **available only for a single material** json _(for multiple "materials" the JSON editor need to be used)_. It **won't be available** for "**hifi_shader_simple**" model.
- Some maps are not supported by the Assistant: lightMap, bumpMap, glossMap _(you will need to use the JSON editor for these)_

We can select many material entities and set the material data for all the selected one at the same time. (But in the case of a multiple selection, the assistant will always start from default value, as it would be tricky to determine which one would be the right one to used as starting point, we can only expect that they wont' match anyway.) We already do something like that when we select the zones for renderWithZones for a multiple selection.

### CODE REVIEW

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR131/Overte-PR131-b6bc6b6.sh
 - https://public.overte.org/build/overte/PR131/Overte-PR131-b6bc6b6.tar.Z
 - https://public.overte.org/build/overte/PR131/Overte-PR131-b6bc6b6.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR131/Overte-PR131-b6bc6b6.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR131/Overte-PR131-b6bc6b6.tar.gz
 - https://public.overte.org/build/overte/PR131/Overte-PR131-b6bc6b6.tar.Z
 - https://public.overte.org/build/overte/PR131/Overte-PR131-b6bc6b6.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR131/Overte-PR131-b6bc6b6.exe

**Review by daleglass — APPROVED** [review]
I looked it over and it looks good to me, but I'm no JS expert, so somebody else's opinion could be nice to have.

**Comment by AleziaKurdis** [comment]
Note: Regarding the code and the syntax, this was already reviewed on vircadia side, reviewed by David. (ref https://github.com/vircadia/vircadia/pull/1658)

**Comment by vegaslon** [comment]
Looks good to me, as long as everyone is ok with not following this 100 in materialAssistant.js , https://github.com/overte-org/overte/blob/master/CODING_STANDARD.md#118-abbreviations-and-acronyms-must-be-uppercase-when-used-in-a-name-or-lowercase-when-used-at-the-beginning-of-a-variable

**Comment by ksuprynowicz** [comment]
Could we change the icon for it into text, for example "material editor"? It took me a moment to figure out, and someone not familiar with Create app might have trouble finding it, especially not knowing that such editor exists.
Another problem I noticed is that colors update correctly when changed, but values like Metallic, Roughness and Opacity don't.
Texture fields update correctly too, so I think it's a problem with sliders.

**Comment by AleziaKurdis** [comment]
> Could we change the icon for it into text, for example "material editor"? It took me a moment to figure out, and someone not familiar with Create app might have trouble finding it, especially not knowing that such editor exists.

I already had to chop the text in the other button just to have this new button fit...
The icon for sure is not the best.
Maybe I can simply use the small button like those for the copy in the spatial tab.

**Comment by AleziaKurdis** [comment]
> Another problem I noticed is that colors update correctly when changed, but values like Metallic, Roughness and Opacity don't.
> Texture fields update correctly too, so I think it's a problem with sliders.

The json get updated... so this is not the sliders

When I change the value in the json editor and do save, this is not getting updated.
This was untouched by me and it was working for age....
It was also working for Vircadia...
the only difference I can see is maybe the change for voxel UI.

Could it be related to this ?
image

**Comment by ksuprynowicz** [comment]
Thanks for looking into it!
I will try running it through a debugger today and see what exactly happens.

**Comment by AleziaKurdis** [comment]
I fixed the issue for the sliders, the value were strings intead of float in the json.

I rename the variable that have an accronym in the name.. to have it in uppercase.

and I reorganized the buttons like this:

image

image

**Comment by ksuprynowicz** [comment]
Thanks!
I just tested it and everything works perfectly. I think this PR is ready for merge.

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR131/Overte-PR131-ff1ee4e.dmg

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR131/Overte-PR131-ff1ee4e.tar.gz
 - https://public.overte.org/build/overte/PR131/Overte-PR131-ff1ee4e.sh
 - https://public.overte.org/build/overte/PR131/Overte-PR131-ff1ee4e.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR131/Overte-PR131-ff1ee4e.exe

**Pull request merged**
