### PR TITLE
Added screenshot format selection with PNG, JPEG and WEBP support

### PR DESCRIPTION
**Pull request by ksuprynowicz**
Format can be selected in general settings. WEBP is very interesting, offiering similar size to JPEG, but better quality.

### CODE REVIEW

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR134/Overte-PR134-bd1fd84.tar.Z
 - https://public.overte.org/build/overte/PR134/Overte-PR134-bd1fd84.sh
 - https://public.overte.org/build/overte/PR134/Overte-PR134-bd1fd84.tar.gz

**windows-2019, full**
 - https://public.overte.org/build/overte/PR134/Overte-PR134-bd1fd84.exe

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR134/Overte-PR134-bd1fd84.tar.gz
 - https://public.overte.org/build/overte/PR134/Overte-PR134-bd1fd84.sh
 - https://public.overte.org/build/overte/PR134/Overte-PR134-bd1fd84.tar.Z

**Comment by JulianGro** [comment]
What is the performance for WEBP?
My experience is that webp is just as small as png on its high compression setting.

**Comment by ksuprynowicz** [comment]
For the same scene PNG is about 2.1 MB, lossy WEBP at 99% quality is 1.3 MB, and lossy JPEG at 99% is 0.9 MB. The problem with PNG is that for some scenes size can go as high as 7.4 MB due to it being lossless.

**Comment by ksuprynowicz** [comment]
My reason for including WEBP is that even at 99% quality, for some scenes compression artifacts in JPEG looked really gross, and seem to be much better in WEBP.

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR134/Overte-PR134-bd1fd84.dmg

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR134/Overte-PR134-863e081.dmg

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR134/Overte-PR134-863e081.tar.Z
 - https://public.overte.org/build/overte/PR134/Overte-PR134-863e081.tar.gz
 - https://public.overte.org/build/overte/PR134/Overte-PR134-863e081.sh

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR134/Overte-PR134-863e081.tar.gz
 - https://public.overte.org/build/overte/PR134/Overte-PR134-863e081.sh
 - https://public.overte.org/build/overte/PR134/Overte-PR134-863e081.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR134/Overte-PR134-863e081.exe

**Review by daleglass — APPROVED** [review]

**Comment by JulianGro** [comment]
Some problems I have encountered while testing:
- By default, no format was selected.
- WebP doesn't work. It just creates an empty file. Maybe system-Qt on Debian Testing doesn't come with WebP support? I have libwebp7, libwebpdemux2, and libwebpmux3 installed.
- The formats should probably have some sort of info next to them. Like "default", "higher quality, bigger filesize", "balanced quality and filesize". The space is certainly there.

**Comment by ksuprynowicz** [comment]
Thanks! It defaults to PNG, but indeed none of the boxes are checked - I will try to fix it. I just tested it on Debian Testing and WEBP works correctly, with image size of about 1.8 MB.
Good point on some additional information. I will add it too.

**Comment by JulianGro** [comment]
Yeah with WebP I get 3.8MiB instead of 5.8MiB with PNG. It does take quite a lot longer to actually take the screenshot however.
With JPEG I get almost no visible interruption. With PNG the screen freezes for almost a second. With WebP the screen freezes for ~2 seconds.

WebP requires `qt5-image-formats-plugins` on runtime.

**Comment by SilverfishVR** [comment]
Tested snapshot app and settings on Windows. Works 👍

Tested the filename/filetype parameter of `Window.takeSnapshot()`,  `Window.takeSecondaryCameraSnapshot()` and `Window.takeSecondaryCameraSnapshot()`. Works 👍

Some general snapshot related observations:
* I noticed that with the snap app, the aspect ratio is limited to just above 17:9, any wider, like my 21:9 monitor gets trunkated, so you may not take the picture you think you are taking, not related to this PR, just a little odd. Using `takeSnapshot()` with no aspect ratio paramerter works as expected.
* Is there a keyboard shortcut for snapshot?
* How about a "show snapshots folder" button in the snap app, like the "reveal log file" button in the log view?

**Comment by JulianGro** [comment]
The hotkey for picture only snapshots is "P".
A show snapshots folder button sounds like a really good idea. But yeah, that is probably for another PR.

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR134/Overte-PR134-dc88080.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR134/Overte-PR134-dc88080.exe

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR134/Overte-PR134-928bdfe.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR134/Overte-PR134-928bdfe.exe

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR134/Overte-PR134-0e3d3f9.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR134/Overte-PR134-0e3d3f9.exe

**Pull request merged**
