### PR TITLE
Update macOS amd64 VCPKG

### PR DESCRIPTION
**Pull request by JulianGro**

### CODE REVIEW

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR138/Overte-PR138-1fcc35f.sh
 - https://public.overte.org/build/overte/PR138/Overte-PR138-1fcc35f.tar.gz
 - https://public.overte.org/build/overte/PR138/Overte-PR138-1fcc35f.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR138/Overte-PR138-1fcc35f.exe

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR138/Overte-PR138-1fcc35f.sh
 - https://public.overte.org/build/overte/PR138/Overte-PR138-1fcc35f.tar.Z
 - https://public.overte.org/build/overte/PR138/Overte-PR138-1fcc35f.tar.gz

**Review by daleglass — APPROVED** [review]

**Review by ksuprynowicz — APPROVED** [review]
Everything looks ok to me.

**Comment by AnimatedMannequin** [comment]
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR138/Overte-PR138-b32e55d.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR138/Overte-PR138-b32e55d.exe

**Comment by JulianGro** [comment]
We seem to have too big of a gap with VCPKG versions.
I will probably all VCPKG builds.

**Pull request closed without merging**
